/* tslint:disable */
/* eslint-disable */
/**
 * AppointmentScheduling API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { Appointment, TelemedicineSession } from "../models/index";
import {
  AppointmentFromJSON,
  AppointmentToJSON,
  TelemedicineSessionFromJSON,
  TelemedicineSessionToJSON,
} from "../models/index";

export interface FindOneAppointmentRequest {
  appointmentId: string;
}

export interface FindOneTelemedicineSessionRequest {
  telemedicineSessionId: string;
}

/**
 * DefaultApi - interface
 *
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApiInterface
   */
  findAllAppointmentsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Appointment>>>;

  /**
   */
  findAllAppointments(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Appointment>>;

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApiInterface
   */
  findAllTelemedicineSessionsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<TelemedicineSession>>>;

  /**
   */
  findAllTelemedicineSessions(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<TelemedicineSession>>;

  /**
   *
   * @param {string} appointmentId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApiInterface
   */
  findOneAppointmentRaw(
    requestParameters: FindOneAppointmentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Appointment>>;

  /**
   */
  findOneAppointment(
    requestParameters: FindOneAppointmentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Appointment>;

  /**
   *
   * @param {string} telemedicineSessionId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApiInterface
   */
  findOneTelemedicineSessionRaw(
    requestParameters: FindOneTelemedicineSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TelemedicineSession>>;

  /**
   */
  findOneTelemedicineSession(
    requestParameters: FindOneTelemedicineSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TelemedicineSession>;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {
  /**
   */
  async findAllAppointmentsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Appointment>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/v1/appointments`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(AppointmentFromJSON),
    );
  }

  /**
   */
  async findAllAppointments(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Appointment>> {
    const response = await this.findAllAppointmentsRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async findAllTelemedicineSessionsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<TelemedicineSession>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/v1/telemedicinesessions`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(TelemedicineSessionFromJSON),
    );
  }

  /**
   */
  async findAllTelemedicineSessions(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<TelemedicineSession>> {
    const response = await this.findAllTelemedicineSessionsRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async findOneAppointmentRaw(
    requestParameters: FindOneAppointmentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Appointment>> {
    if (requestParameters["appointmentId"] == null) {
      throw new runtime.RequiredError(
        "appointmentId",
        'Required parameter "appointmentId" was null or undefined when calling findOneAppointment().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/v1/appointments/{appointmentId}`;
    urlPath = urlPath.replace(
      `{${"appointmentId"}}`,
      encodeURIComponent(String(requestParameters["appointmentId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AppointmentFromJSON(jsonValue),
    );
  }

  /**
   */
  async findOneAppointment(
    requestParameters: FindOneAppointmentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Appointment> {
    const response = await this.findOneAppointmentRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async findOneTelemedicineSessionRaw(
    requestParameters: FindOneTelemedicineSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TelemedicineSession>> {
    if (requestParameters["telemedicineSessionId"] == null) {
      throw new runtime.RequiredError(
        "telemedicineSessionId",
        'Required parameter "telemedicineSessionId" was null or undefined when calling findOneTelemedicineSession().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/v1/telemedicinesessions/{telemedicineSessionId}`;
    urlPath = urlPath.replace(
      `{${"telemedicineSessionId"}}`,
      encodeURIComponent(String(requestParameters["telemedicineSessionId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TelemedicineSessionFromJSON(jsonValue),
    );
  }

  /**
   */
  async findOneTelemedicineSession(
    requestParameters: FindOneTelemedicineSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TelemedicineSession> {
    const response = await this.findOneTelemedicineSessionRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
