# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    commit-message:
          prefix: "chore(deps)"
    schedule:
      interval: "weekly"
    groups:
      # Group all Go module updates together
      all-go-modules:
        patterns:
          - "*"
      
  - package-ecosystem: "npm"
    directory: "api/frontend" # Location of package manifests
    commit-message:
          prefix: "chore(deps)"
    schedule:
      interval: "weekly"
    groups:
      # Group all npm updates together
      all-npm-dependencies:
        patterns:
          - "*"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/build/docker" # Location of Dockerfiles
    commit-message:
          prefix: "chore(deps)"
    schedule:
      interval: "weekly"
    groups:
      # Group all Docker updates together
      all-dockerfiles:
        patterns:
          - "*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of workflow files
    commit-message:
          prefix: "chore(deps)"
    schedule:
      interval: "weekly"
    groups:
      # Group all GitHub Actions updates together
      all-github-actions:
        patterns:
          - "*"

  # Enable version updates for Docker Compose files
  - package-ecosystem: "docker-compose"
    directory: "/deploy/compose" # Location of docker-compose.yml files
    commit-message:
          prefix: "chore(deps)"
    schedule:
      interval: "weekly"
    groups:
      # Group all Docker Compose updates together
      all-docker-compose:
        patterns:
          - "*"

  # Enable version updates for Python dependencies in the docs folder
  - package-ecosystem: "pip"
    directory: "/docs" # Location of requirements.txt or pyproject.toml
    commit-message:
          prefix: "chore(deps)"
    schedule:
      interval: "weekly"
    groups:
      # Group all Python updates together
      all-python-dependencies:
        patterns:
          - "*"