// Package api_client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api_client

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Appointment Represents a scheduled appointment at the clinic
type Appointment struct {
	AppointmentId   *string `json:"appointment_id,omitempty"`
	AppointmentType *string `json:"appointment_type,omitempty"`
	DurationMinutes *int32  `json:"duration_minutes,omitempty"`
	IsTelemedicine  *bool   `json:"is_telemedicine,omitempty"`
	Notes           *string `json:"notes,omitempty"`
	OwnerId         *string `json:"owner_id,omitempty"`
	PetId           *string `json:"pet_id,omitempty"`
	ScheduledDate   *string `json:"scheduled_date,omitempty"`
	ScheduledTime   *string `json:"scheduled_time,omitempty"`
	Status          *string `json:"status,omitempty"`
	VeterinarianId  *string `json:"veterinarian_id,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    *int32  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// TelemedicineSession Represents a telemedicine session linked to an appointment
type TelemedicineSession struct {
	AppointmentId *string `json:"appointment_id,omitempty"`
	EndedAt       *string `json:"ended_at,omitempty"`
	SessionId     *string `json:"session_id,omitempty"`
	SessionUrl    *string `json:"session_url,omitempty"`
	StartedAt     *string `json:"started_at,omitempty"`
	Status        *string `json:"status,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// FindAllAppointments request
	FindAllAppointments(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindOneAppointment request
	FindOneAppointment(ctx context.Context, appointmentId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindAllTelemedicineSessions request
	FindAllTelemedicineSessions(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindOneTelemedicineSession request
	FindOneTelemedicineSession(ctx context.Context, telemedicineSessionId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) FindAllAppointments(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindAllAppointmentsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindOneAppointment(ctx context.Context, appointmentId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindOneAppointmentRequest(c.Server, appointmentId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindAllTelemedicineSessions(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindAllTelemedicineSessionsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindOneTelemedicineSession(ctx context.Context, telemedicineSessionId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindOneTelemedicineSessionRequest(c.Server, telemedicineSessionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewFindAllAppointmentsRequest generates requests for FindAllAppointments
func NewFindAllAppointmentsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/appointments")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindOneAppointmentRequest generates requests for FindOneAppointment
func NewFindOneAppointmentRequest(server string, appointmentId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "appointmentId", runtime.ParamLocationPath, appointmentId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/appointments/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindAllTelemedicineSessionsRequest generates requests for FindAllTelemedicineSessions
func NewFindAllTelemedicineSessionsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/telemedicinesessions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindOneTelemedicineSessionRequest generates requests for FindOneTelemedicineSession
func NewFindOneTelemedicineSessionRequest(server string, telemedicineSessionId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "telemedicineSessionId", runtime.ParamLocationPath, telemedicineSessionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/telemedicinesessions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// FindAllAppointmentsWithResponse request
	FindAllAppointmentsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllAppointmentsResponse, error)

	// FindOneAppointmentWithResponse request
	FindOneAppointmentWithResponse(ctx context.Context, appointmentId string, reqEditors ...RequestEditorFn) (*FindOneAppointmentResponse, error)

	// FindAllTelemedicineSessionsWithResponse request
	FindAllTelemedicineSessionsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllTelemedicineSessionsResponse, error)

	// FindOneTelemedicineSessionWithResponse request
	FindOneTelemedicineSessionWithResponse(ctx context.Context, telemedicineSessionId string, reqEditors ...RequestEditorFn) (*FindOneTelemedicineSessionResponse, error)
}

type FindAllAppointmentsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Appointment
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindAllAppointmentsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindAllAppointmentsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindOneAppointmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Appointment
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindOneAppointmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindOneAppointmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindAllTelemedicineSessionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]TelemedicineSession
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindAllTelemedicineSessionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindAllTelemedicineSessionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindOneTelemedicineSessionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TelemedicineSession
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindOneTelemedicineSessionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindOneTelemedicineSessionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// FindAllAppointmentsWithResponse request returning *FindAllAppointmentsResponse
func (c *ClientWithResponses) FindAllAppointmentsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllAppointmentsResponse, error) {
	rsp, err := c.FindAllAppointments(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindAllAppointmentsResponse(rsp)
}

// FindOneAppointmentWithResponse request returning *FindOneAppointmentResponse
func (c *ClientWithResponses) FindOneAppointmentWithResponse(ctx context.Context, appointmentId string, reqEditors ...RequestEditorFn) (*FindOneAppointmentResponse, error) {
	rsp, err := c.FindOneAppointment(ctx, appointmentId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindOneAppointmentResponse(rsp)
}

// FindAllTelemedicineSessionsWithResponse request returning *FindAllTelemedicineSessionsResponse
func (c *ClientWithResponses) FindAllTelemedicineSessionsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllTelemedicineSessionsResponse, error) {
	rsp, err := c.FindAllTelemedicineSessions(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindAllTelemedicineSessionsResponse(rsp)
}

// FindOneTelemedicineSessionWithResponse request returning *FindOneTelemedicineSessionResponse
func (c *ClientWithResponses) FindOneTelemedicineSessionWithResponse(ctx context.Context, telemedicineSessionId string, reqEditors ...RequestEditorFn) (*FindOneTelemedicineSessionResponse, error) {
	rsp, err := c.FindOneTelemedicineSession(ctx, telemedicineSessionId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindOneTelemedicineSessionResponse(rsp)
}

// ParseFindAllAppointmentsResponse parses an HTTP response from a FindAllAppointmentsWithResponse call
func ParseFindAllAppointmentsResponse(rsp *http.Response) (*FindAllAppointmentsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindAllAppointmentsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Appointment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindOneAppointmentResponse parses an HTTP response from a FindOneAppointmentWithResponse call
func ParseFindOneAppointmentResponse(rsp *http.Response) (*FindOneAppointmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindOneAppointmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Appointment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindAllTelemedicineSessionsResponse parses an HTTP response from a FindAllTelemedicineSessionsWithResponse call
func ParseFindAllTelemedicineSessionsResponse(rsp *http.Response) (*FindAllTelemedicineSessionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindAllTelemedicineSessionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []TelemedicineSession
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindOneTelemedicineSessionResponse parses an HTTP response from a FindOneTelemedicineSessionWithResponse call
func ParseFindOneTelemedicineSessionResponse(rsp *http.Response) (*FindOneTelemedicineSessionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindOneTelemedicineSessionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TelemedicineSession
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
