/* tslint:disable */
/* eslint-disable */
/**
 * BillingAndPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Represents a payment transaction against an invoice
 * @export
 * @interface Payment
 */
export interface Payment {
  /**
   *
   * @type {string}
   * @memberof Payment
   */
  paymentId?: string;
  /**
   *
   * @type {string}
   * @memberof Payment
   */
  invoiceId?: string;
  /**
   *
   * @type {string}
   * @memberof Payment
   */
  ownerId?: string;
  /**
   *
   * @type {number}
   * @memberof Payment
   */
  amountPaid?: number;
  /**
   *
   * @type {string}
   * @memberof Payment
   */
  paymentMethod?: string;
  /**
   *
   * @type {string}
   * @memberof Payment
   */
  paymentDate?: string;
  /**
   *
   * @type {string}
   * @memberof Payment
   */
  status?: string;
}

/**
 * Check if a given object implements the Payment interface.
 */
export function instanceOfPayment(value: object): value is Payment {
  return true;
}

export function PaymentFromJSON(json: any): Payment {
  return PaymentFromJSONTyped(json, false);
}

export function PaymentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Payment {
  if (json == null) {
    return json;
  }
  return {
    paymentId: json["payment_id"] == null ? undefined : json["payment_id"],
    invoiceId: json["invoice_id"] == null ? undefined : json["invoice_id"],
    ownerId: json["owner_id"] == null ? undefined : json["owner_id"],
    amountPaid: json["amount_paid"] == null ? undefined : json["amount_paid"],
    paymentMethod:
      json["payment_method"] == null ? undefined : json["payment_method"],
    paymentDate:
      json["payment_date"] == null ? undefined : json["payment_date"],
    status: json["status"] == null ? undefined : json["status"],
  };
}

export function PaymentToJSON(json: any): Payment {
  return PaymentToJSONTyped(json, false);
}

export function PaymentToJSONTyped(
  value?: Payment | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    payment_id: value["paymentId"],
    invoice_id: value["invoiceId"],
    owner_id: value["ownerId"],
    amount_paid: value["amountPaid"],
    payment_method: value["paymentMethod"],
    payment_date: value["paymentDate"],
    status: value["status"],
  };
}
