/* tslint:disable */
/* eslint-disable */
/**
 * BillingAndPayments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ProcessPayment
 */
export interface ProcessPayment {
  /**
   *
   * @type {string}
   * @memberof ProcessPayment
   */
  invoiceId?: string;
  /**
   *
   * @type {string}
   * @memberof ProcessPayment
   */
  ownerId?: string;
  /**
   *
   * @type {number}
   * @memberof ProcessPayment
   */
  amountPaid?: number;
  /**
   *
   * @type {string}
   * @memberof ProcessPayment
   */
  paymentMethod?: string;
}

/**
 * Check if a given object implements the ProcessPayment interface.
 */
export function instanceOfProcessPayment(
  value: object,
): value is ProcessPayment {
  return true;
}

export function ProcessPaymentFromJSON(json: any): ProcessPayment {
  return ProcessPaymentFromJSONTyped(json, false);
}

export function ProcessPaymentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProcessPayment {
  if (json == null) {
    return json;
  }
  return {
    invoiceId: json["invoiceId"] == null ? undefined : json["invoiceId"],
    ownerId: json["ownerId"] == null ? undefined : json["ownerId"],
    amountPaid: json["amountPaid"] == null ? undefined : json["amountPaid"],
    paymentMethod:
      json["paymentMethod"] == null ? undefined : json["paymentMethod"],
  };
}

export function ProcessPaymentToJSON(json: any): ProcessPayment {
  return ProcessPaymentToJSONTyped(json, false);
}

export function ProcessPaymentToJSONTyped(
  value?: ProcessPayment | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    invoiceId: value["invoiceId"],
    ownerId: value["ownerId"],
    amountPaid: value["amountPaid"],
    paymentMethod: value["paymentMethod"],
  };
}
