package config_test

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"

	"github.com/cooperlutz/go-full/app/config"
)

// TestLoadConfigFromEnvVars tests the LoadConfigFromEnvVars function.
func TestLoadConfigFromEnvVars(t *testing.T) {
	// Arrange
	tests := []struct {
		name        string
		envVars     map[string]string
		expectedCfg config.Config
	}{
		{
			name: "success",
			envVars: map[string]string{
				"HTTP_PORT":              "8080",
				"DB_TYPE":                "postgres",
				"DB_USER":                "user",
				"DB_PASSWORD":            "THIS_IS_NOT_A_REAL_PASSWORD",
				"DB_HOST":                "db",
				"DB_PORT":                "5432",
				"DB_DBNAME":              "db",
				"DB_SSLMODE":             "disable",
				"OBSERVE_TRACE_ENDPOINT": "localhost:4317",
				"SEC_JWT_PRIVATE_KEY":    "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ242cmFOdHdBVXh0amoKSVlwa3RXTDR3WktmOWE2czg1NHZ4cFdhQlZwVzY4U05zRWRCZEIwRmR4RTQ3NThsTUJHWk5uNmxaMGtaK3BJawpKZkFXRGszQlgzcU5ONWdpRFc5TVVsL05PNHFsRnhla090MG11eFFWenpLM0VMS2dmK0hwZ01BOG5BNzYvYml6Ckp0aisxUkVnNGRRSHlMT3hjWElEMEMyVm5ORnVGN3QvSXBjZjFsSStsV3NzMkxKbkF5MXdKVlZ5VzAvV3F5dmQKVm0rWU43c0lZU2RDK0piWW5XdSt6QjBSbUY2WDRKSzBRVDBOeER3R3A1ajJSQXNlYi9EYm5JdzZCZmtNTXc4dwpyOWI1dVJkTVZBUHdoMXpaRmRTSGhlcEJoYTZVQVVVMWZTaHVkZDRJcnBiVklaVmkxUjYwWmpaVElaNGVpME9LCmRSL2pxRXVCQWdNQkFBRUNnZ0VBTnNxL0FPVXJFSnlHSHk5Tm9ta1J2NHdpbFRHczZ1Q2Z5SVVyUWRQblU1K2gKUm42ejhhYTY1WktodXd0dHljdXlvbVVHMUdBc21WNkxHMktKd2hpdXhKK3NOTEprWVJBek5odFhDWGdaV0o5OQpabWlTeTFXV1N6dU9GL0JKNlZkeFZ5bGRFU24zTlcxZlBJNDdsb1BlRC9YQW96MlpiUmhRbE8vMFAvS280QncwClpWN1FNTUhxaFJoWmhLOGVNYWZmVDdUdjdzRGhyb2daTitXR3VFVUlRZTloWkk1NTRxaTZuWDdMTHJ2RURVRGsKZ2RFMURNWXhYVm1PM1lpWHRmanhnV1plSlU1empjZzhEOXErWVBPV3NEU3hPOVpzUmMzTjlKV1F2bDViemIwegp0MmxhMEhnRHNSZTVpUjBuSzdLRHlGVXZVZjNvMWF5M2YxYW5Rc1p6WlFLQmdRRGxHOURmSUtHVUlYMjlabHNMCkNaaVhtRWRENEJYRFZRS2xTR1VXTlVnak1zL1NrM3JkbStYd2ppeXE0b3BVNVI1a3hzZklrUW1DU0c5Rk5hMkYKa2NmQlpjZ0lHdXJzNC9IWGkyVzdEVWRYQnlHSHVWa0RPQzV2VTdOc0thNmx5dHlYTXZLRjBvT0Z3bnFmRlNwSwpySlZLMFB2WlRQQWJUUmFqSVc4akdSWW1sd0tCZ1FDN29EbW1lZnE2VVpaQXZqWVVvSU5YZmNWTEFBQUtPNmVNCkRYaE5qTEdaMVhQTFhla0d3b0ppOGlwS0pYMlpLSm9PTWlyaEFTK0plQzIzNEcvMXkza1Y4aW1jaU1kUDNNckUKSDliS0lSMytoYUh4SjJ0YVlVYnRSYkJQdDkzLzE1cXNLTGRiTGlhUGVLVFNxbVhnYVVGdEVqajJrdjVmZVFmMgp0V1dJYW42NXB3S0JnUUN6T2VOWDZXcjlPb1htMkY5NGJ2VlVBZWdlRFBwNVo5TStBVGd5KzFPSFZZU0dNcUQzCkk3SHBVUTlZVHdmd0NaeVJNWCt3UXVXeGFZRENINCt5NGF2bWV2elVlbG8xSHN4ZDFjcXJYV1Bsak1xS0psQ2YKMkI5Ykw1czRqaEwxMTVCaEo1WFpZaWxKUmk0dXJKdjg5cTJEYmFEWENQejhIbjRLOTJpOWlDNXYyUUtCZ0E4agpsb05BUkdMVVFuTm01YVkwYldTWjJWbDczb1QwMjBnSnJqTlRydURpd0QwZ2pyVGs3UEJlNmRxaHU4aW41Z1pQCk5mYUJ5ZndsbmtxLzZVakQ2amxER09od2dPU0l4RE9lL2czQkxsSmpKZlgzWUVvaW56NTE2UXdGb2Z3S3dZZ3kKb05qU21IbnJHaUdGYmtMMU96bzV4aTdmSFhkR3BNWGJUUjM4dWN6eEFvR0FkbUQyVFltSE1BUU5kNlJGYTd0dAp3NHBSRW5seWxTY3VPYXVkQ2h6enF0OERyb29EaWVENFhvTGQvdE1UcUlkYTNRQ05LM0ZVaWhXdUdyUEFKa01yCjZYcU96a3NCcnVRcDR4SmdjbWZSb016MGZTRG5sMHNSOFd3K3lMVWlrMVdzSlhMVUJVWnBpaDNlWmh4REw0NGwKaHI0L0lpTXdqVkZZcDE3VnVEZnk2Umc9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K",
			},
			expectedCfg: config.Config{
				App: config.App{
					Name:    "go-full",
					Version: "",
				},
				HTTP: config.HTTP{
					Port: "8080",
				},
				DB: config.DB{
					Type:     "postgres",
					Host:     "db",
					Port:     5432,
					User:     "user",
					Password: "THIS_IS_NOT_A_REAL_PASSWORD",
					DBName:   "db",
					SSLMode:  "disable",
				},
				Telemetry: config.Telemetry{
					TraceEndpoint: "localhost:4317",
				},
				Security: config.Security{
					Base64EncodedJWTPrivateKeyPEM: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ242cmFOdHdBVXh0amoKSVlwa3RXTDR3WktmOWE2czg1NHZ4cFdhQlZwVzY4U05zRWRCZEIwRmR4RTQ3NThsTUJHWk5uNmxaMGtaK3BJawpKZkFXRGszQlgzcU5ONWdpRFc5TVVsL05PNHFsRnhla090MG11eFFWenpLM0VMS2dmK0hwZ01BOG5BNzYvYml6Ckp0aisxUkVnNGRRSHlMT3hjWElEMEMyVm5ORnVGN3QvSXBjZjFsSStsV3NzMkxKbkF5MXdKVlZ5VzAvV3F5dmQKVm0rWU43c0lZU2RDK0piWW5XdSt6QjBSbUY2WDRKSzBRVDBOeER3R3A1ajJSQXNlYi9EYm5JdzZCZmtNTXc4dwpyOWI1dVJkTVZBUHdoMXpaRmRTSGhlcEJoYTZVQVVVMWZTaHVkZDRJcnBiVklaVmkxUjYwWmpaVElaNGVpME9LCmRSL2pxRXVCQWdNQkFBRUNnZ0VBTnNxL0FPVXJFSnlHSHk5Tm9ta1J2NHdpbFRHczZ1Q2Z5SVVyUWRQblU1K2gKUm42ejhhYTY1WktodXd0dHljdXlvbVVHMUdBc21WNkxHMktKd2hpdXhKK3NOTEprWVJBek5odFhDWGdaV0o5OQpabWlTeTFXV1N6dU9GL0JKNlZkeFZ5bGRFU24zTlcxZlBJNDdsb1BlRC9YQW96MlpiUmhRbE8vMFAvS280QncwClpWN1FNTUhxaFJoWmhLOGVNYWZmVDdUdjdzRGhyb2daTitXR3VFVUlRZTloWkk1NTRxaTZuWDdMTHJ2RURVRGsKZ2RFMURNWXhYVm1PM1lpWHRmanhnV1plSlU1empjZzhEOXErWVBPV3NEU3hPOVpzUmMzTjlKV1F2bDViemIwegp0MmxhMEhnRHNSZTVpUjBuSzdLRHlGVXZVZjNvMWF5M2YxYW5Rc1p6WlFLQmdRRGxHOURmSUtHVUlYMjlabHNMCkNaaVhtRWRENEJYRFZRS2xTR1VXTlVnak1zL1NrM3JkbStYd2ppeXE0b3BVNVI1a3hzZklrUW1DU0c5Rk5hMkYKa2NmQlpjZ0lHdXJzNC9IWGkyVzdEVWRYQnlHSHVWa0RPQzV2VTdOc0thNmx5dHlYTXZLRjBvT0Z3bnFmRlNwSwpySlZLMFB2WlRQQWJUUmFqSVc4akdSWW1sd0tCZ1FDN29EbW1lZnE2VVpaQXZqWVVvSU5YZmNWTEFBQUtPNmVNCkRYaE5qTEdaMVhQTFhla0d3b0ppOGlwS0pYMlpLSm9PTWlyaEFTK0plQzIzNEcvMXkza1Y4aW1jaU1kUDNNckUKSDliS0lSMytoYUh4SjJ0YVlVYnRSYkJQdDkzLzE1cXNLTGRiTGlhUGVLVFNxbVhnYVVGdEVqajJrdjVmZVFmMgp0V1dJYW42NXB3S0JnUUN6T2VOWDZXcjlPb1htMkY5NGJ2VlVBZWdlRFBwNVo5TStBVGd5KzFPSFZZU0dNcUQzCkk3SHBVUTlZVHdmd0NaeVJNWCt3UXVXeGFZRENINCt5NGF2bWV2elVlbG8xSHN4ZDFjcXJYV1Bsak1xS0psQ2YKMkI5Ykw1czRqaEwxMTVCaEo1WFpZaWxKUmk0dXJKdjg5cTJEYmFEWENQejhIbjRLOTJpOWlDNXYyUUtCZ0E4agpsb05BUkdMVVFuTm01YVkwYldTWjJWbDczb1QwMjBnSnJqTlRydURpd0QwZ2pyVGs3UEJlNmRxaHU4aW41Z1pQCk5mYUJ5ZndsbmtxLzZVakQ2amxER09od2dPU0l4RE9lL2czQkxsSmpKZlgzWUVvaW56NTE2UXdGb2Z3S3dZZ3kKb05qU21IbnJHaUdGYmtMMU96bzV4aTdmSFhkR3BNWGJUUjM4dWN6eEFvR0FkbUQyVFltSE1BUU5kNlJGYTd0dAp3NHBSRW5seWxTY3VPYXVkQ2h6enF0OERyb29EaWVENFhvTGQvdE1UcUlkYTNRQ05LM0ZVaWhXdUdyUEFKa01yCjZYcU96a3NCcnVRcDR4SmdjbWZSb016MGZTRG5sMHNSOFd3K3lMVWlrMVdzSlhMVUJVWnBpaDNlWmh4REw0NGwKaHI0L0lpTXdqVkZZcDE3VnVEZnk2Umc9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K",
					AccessTokenTTL:                time.Duration(15) * time.Minute,
					RefreshTokenTTL:               time.Hour * 24 * 7,
				},
			},
		},
		{
			name: "test type conversion default values: invalid DB_PORT & METRICS_ENABLED is overriden with default",
			envVars: map[string]string{
				"HTTP_PORT":              "8080",
				"DB_TYPE":                "postgres",
				"DB_USER":                "user",
				"DB_PASSWORD":            "THIS_IS_NOT_A_REAL_PASSWORD",
				"DB_HOST":                "db",
				"DB_PORT":                "this-is-not-an-int",
				"DB_DBNAME":              "db",
				"DB_SSLMODE":             "disable",
				"OBSERVE_TRACE_ENDPOINT": "localhost:4317",
				"SEC_JWT_PRIVATE_KEY":    "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ242cmFOdHdBVXh0amoKSVlwa3RXTDR3WktmOWE2czg1NHZ4cFdhQlZwVzY4U05zRWRCZEIwRmR4RTQ3NThsTUJHWk5uNmxaMGtaK3BJawpKZkFXRGszQlgzcU5ONWdpRFc5TVVsL05PNHFsRnhla090MG11eFFWenpLM0VMS2dmK0hwZ01BOG5BNzYvYml6Ckp0aisxUkVnNGRRSHlMT3hjWElEMEMyVm5ORnVGN3QvSXBjZjFsSStsV3NzMkxKbkF5MXdKVlZ5VzAvV3F5dmQKVm0rWU43c0lZU2RDK0piWW5XdSt6QjBSbUY2WDRKSzBRVDBOeER3R3A1ajJSQXNlYi9EYm5JdzZCZmtNTXc4dwpyOWI1dVJkTVZBUHdoMXpaRmRTSGhlcEJoYTZVQVVVMWZTaHVkZDRJcnBiVklaVmkxUjYwWmpaVElaNGVpME9LCmRSL2pxRXVCQWdNQkFBRUNnZ0VBTnNxL0FPVXJFSnlHSHk5Tm9ta1J2NHdpbFRHczZ1Q2Z5SVVyUWRQblU1K2gKUm42ejhhYTY1WktodXd0dHljdXlvbVVHMUdBc21WNkxHMktKd2hpdXhKK3NOTEprWVJBek5odFhDWGdaV0o5OQpabWlTeTFXV1N6dU9GL0JKNlZkeFZ5bGRFU24zTlcxZlBJNDdsb1BlRC9YQW96MlpiUmhRbE8vMFAvS280QncwClpWN1FNTUhxaFJoWmhLOGVNYWZmVDdUdjdzRGhyb2daTitXR3VFVUlRZTloWkk1NTRxaTZuWDdMTHJ2RURVRGsKZ2RFMURNWXhYVm1PM1lpWHRmanhnV1plSlU1empjZzhEOXErWVBPV3NEU3hPOVpzUmMzTjlKV1F2bDViemIwegp0MmxhMEhnRHNSZTVpUjBuSzdLRHlGVXZVZjNvMWF5M2YxYW5Rc1p6WlFLQmdRRGxHOURmSUtHVUlYMjlabHNMCkNaaVhtRWRENEJYRFZRS2xTR1VXTlVnak1zL1NrM3JkbStYd2ppeXE0b3BVNVI1a3hzZklrUW1DU0c5Rk5hMkYKa2NmQlpjZ0lHdXJzNC9IWGkyVzdEVWRYQnlHSHVWa0RPQzV2VTdOc0thNmx5dHlYTXZLRjBvT0Z3bnFmRlNwSwpySlZLMFB2WlRQQWJUUmFqSVc4akdSWW1sd0tCZ1FDN29EbW1lZnE2VVpaQXZqWVVvSU5YZmNWTEFBQUtPNmVNCkRYaE5qTEdaMVhQTFhla0d3b0ppOGlwS0pYMlpLSm9PTWlyaEFTK0plQzIzNEcvMXkza1Y4aW1jaU1kUDNNckUKSDliS0lSMytoYUh4SjJ0YVlVYnRSYkJQdDkzLzE1cXNLTGRiTGlhUGVLVFNxbVhnYVVGdEVqajJrdjVmZVFmMgp0V1dJYW42NXB3S0JnUUN6T2VOWDZXcjlPb1htMkY5NGJ2VlVBZWdlRFBwNVo5TStBVGd5KzFPSFZZU0dNcUQzCkk3SHBVUTlZVHdmd0NaeVJNWCt3UXVXeGFZRENINCt5NGF2bWV2elVlbG8xSHN4ZDFjcXJYV1Bsak1xS0psQ2YKMkI5Ykw1czRqaEwxMTVCaEo1WFpZaWxKUmk0dXJKdjg5cTJEYmFEWENQejhIbjRLOTJpOWlDNXYyUUtCZ0E4agpsb05BUkdMVVFuTm01YVkwYldTWjJWbDczb1QwMjBnSnJqTlRydURpd0QwZ2pyVGs3UEJlNmRxaHU4aW41Z1pQCk5mYUJ5ZndsbmtxLzZVakQ2amxER09od2dPU0l4RE9lL2czQkxsSmpKZlgzWUVvaW56NTE2UXdGb2Z3S3dZZ3kKb05qU21IbnJHaUdGYmtMMU96bzV4aTdmSFhkR3BNWGJUUjM4dWN6eEFvR0FkbUQyVFltSE1BUU5kNlJGYTd0dAp3NHBSRW5seWxTY3VPYXVkQ2h6enF0OERyb29EaWVENFhvTGQvdE1UcUlkYTNRQ05LM0ZVaWhXdUdyUEFKa01yCjZYcU96a3NCcnVRcDR4SmdjbWZSb016MGZTRG5sMHNSOFd3K3lMVWlrMVdzSlhMVUJVWnBpaDNlWmh4REw0NGwKaHI0L0lpTXdqVkZZcDE3VnVEZnk2Umc9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K",
			},
			expectedCfg: config.Config{
				App: config.App{
					Name:    "go-full",
					Version: "",
				},
				HTTP: config.HTTP{
					Port: "8080",
				},
				DB: config.DB{
					Type:     "postgres",
					Host:     "db",
					Port:     5432,
					User:     "user",
					Password: "THIS_IS_NOT_A_REAL_PASSWORD",
					DBName:   "db",
					SSLMode:  "disable",
				},
				Telemetry: config.Telemetry{
					TraceEndpoint: "localhost:4317",
				},
				Security: config.Security{
					Base64EncodedJWTPrivateKeyPEM: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ242cmFOdHdBVXh0amoKSVlwa3RXTDR3WktmOWE2czg1NHZ4cFdhQlZwVzY4U05zRWRCZEIwRmR4RTQ3NThsTUJHWk5uNmxaMGtaK3BJawpKZkFXRGszQlgzcU5ONWdpRFc5TVVsL05PNHFsRnhla090MG11eFFWenpLM0VMS2dmK0hwZ01BOG5BNzYvYml6Ckp0aisxUkVnNGRRSHlMT3hjWElEMEMyVm5ORnVGN3QvSXBjZjFsSStsV3NzMkxKbkF5MXdKVlZ5VzAvV3F5dmQKVm0rWU43c0lZU2RDK0piWW5XdSt6QjBSbUY2WDRKSzBRVDBOeER3R3A1ajJSQXNlYi9EYm5JdzZCZmtNTXc4dwpyOWI1dVJkTVZBUHdoMXpaRmRTSGhlcEJoYTZVQVVVMWZTaHVkZDRJcnBiVklaVmkxUjYwWmpaVElaNGVpME9LCmRSL2pxRXVCQWdNQkFBRUNnZ0VBTnNxL0FPVXJFSnlHSHk5Tm9ta1J2NHdpbFRHczZ1Q2Z5SVVyUWRQblU1K2gKUm42ejhhYTY1WktodXd0dHljdXlvbVVHMUdBc21WNkxHMktKd2hpdXhKK3NOTEprWVJBek5odFhDWGdaV0o5OQpabWlTeTFXV1N6dU9GL0JKNlZkeFZ5bGRFU24zTlcxZlBJNDdsb1BlRC9YQW96MlpiUmhRbE8vMFAvS280QncwClpWN1FNTUhxaFJoWmhLOGVNYWZmVDdUdjdzRGhyb2daTitXR3VFVUlRZTloWkk1NTRxaTZuWDdMTHJ2RURVRGsKZ2RFMURNWXhYVm1PM1lpWHRmanhnV1plSlU1empjZzhEOXErWVBPV3NEU3hPOVpzUmMzTjlKV1F2bDViemIwegp0MmxhMEhnRHNSZTVpUjBuSzdLRHlGVXZVZjNvMWF5M2YxYW5Rc1p6WlFLQmdRRGxHOURmSUtHVUlYMjlabHNMCkNaaVhtRWRENEJYRFZRS2xTR1VXTlVnak1zL1NrM3JkbStYd2ppeXE0b3BVNVI1a3hzZklrUW1DU0c5Rk5hMkYKa2NmQlpjZ0lHdXJzNC9IWGkyVzdEVWRYQnlHSHVWa0RPQzV2VTdOc0thNmx5dHlYTXZLRjBvT0Z3bnFmRlNwSwpySlZLMFB2WlRQQWJUUmFqSVc4akdSWW1sd0tCZ1FDN29EbW1lZnE2VVpaQXZqWVVvSU5YZmNWTEFBQUtPNmVNCkRYaE5qTEdaMVhQTFhla0d3b0ppOGlwS0pYMlpLSm9PTWlyaEFTK0plQzIzNEcvMXkza1Y4aW1jaU1kUDNNckUKSDliS0lSMytoYUh4SjJ0YVlVYnRSYkJQdDkzLzE1cXNLTGRiTGlhUGVLVFNxbVhnYVVGdEVqajJrdjVmZVFmMgp0V1dJYW42NXB3S0JnUUN6T2VOWDZXcjlPb1htMkY5NGJ2VlVBZWdlRFBwNVo5TStBVGd5KzFPSFZZU0dNcUQzCkk3SHBVUTlZVHdmd0NaeVJNWCt3UXVXeGFZRENINCt5NGF2bWV2elVlbG8xSHN4ZDFjcXJYV1Bsak1xS0psQ2YKMkI5Ykw1czRqaEwxMTVCaEo1WFpZaWxKUmk0dXJKdjg5cTJEYmFEWENQejhIbjRLOTJpOWlDNXYyUUtCZ0E4agpsb05BUkdMVVFuTm01YVkwYldTWjJWbDczb1QwMjBnSnJqTlRydURpd0QwZ2pyVGs3UEJlNmRxaHU4aW41Z1pQCk5mYUJ5ZndsbmtxLzZVakQ2amxER09od2dPU0l4RE9lL2czQkxsSmpKZlgzWUVvaW56NTE2UXdGb2Z3S3dZZ3kKb05qU21IbnJHaUdGYmtMMU96bzV4aTdmSFhkR3BNWGJUUjM4dWN6eEFvR0FkbUQyVFltSE1BUU5kNlJGYTd0dAp3NHBSRW5seWxTY3VPYXVkQ2h6enF0OERyb29EaWVENFhvTGQvdE1UcUlkYTNRQ05LM0ZVaWhXdUdyUEFKa01yCjZYcU96a3NCcnVRcDR4SmdjbWZSb016MGZTRG5sMHNSOFd3K3lMVWlrMVdzSlhMVUJVWnBpaDNlWmh4REw0NGwKaHI0L0lpTXdqVkZZcDE3VnVEZnk2Umc9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K",
					AccessTokenTTL:                time.Duration(15) * time.Minute,
					RefreshTokenTTL:               time.Hour * 24 * 7,
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Arrange
			for key, value := range tt.envVars {
				t.Setenv(key, value)
			}
			// Act
			cfg, err := config.LoadConfigFromEnvVars()
			// Assert
			assert.NoError(t, err)
			assert.Equal(t, tt.expectedCfg, cfg)
		})
	}
}

// TestLoadConfigFromEnvVars_MissingVars tests the LoadConfigFromEnvVars function.
func TestLoadConfigFromEnvVars_MissingVars(t *testing.T) {
	// Arrange
	tests := []struct {
		name        string
		envVars     map[string]string
		expectedCfg config.Config
		expectedErr error
	}{
		{
			name: "success",
			envVars: map[string]string{
				"HTTP_PORT":              "",
				"DB_TYPE":                "postgres",
				"DB_USER":                "user",
				"DB_PASSWORD":            "THIS_IS_NOT_A_REAL_PASSWORD",
				"DB_HOST":                "db",
				"DB_PORT":                "5432",
				"DB_DBNAME":              "db",
				"DB_SSLMODE":             "disable",
				"OBSERVE_TRACE_ENDPOINT": "localhost:4317",
				"SEC_JWT_PRIVATE_KEY":    "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ242cmFOdHdBVXh0amoKSVlwa3RXTDR3WktmOWE2czg1NHZ4cFdhQlZwVzY4U05zRWRCZEIwRmR4RTQ3NThsTUJHWk5uNmxaMGtaK3BJawpKZkFXRGszQlgzcU5ONWdpRFc5TVVsL05PNHFsRnhla090MG11eFFWenpLM0VMS2dmK0hwZ01BOG5BNzYvYml6Ckp0aisxUkVnNGRRSHlMT3hjWElEMEMyVm5ORnVGN3QvSXBjZjFsSStsV3NzMkxKbkF5MXdKVlZ5VzAvV3F5dmQKVm0rWU43c0lZU2RDK0piWW5XdSt6QjBSbUY2WDRKSzBRVDBOeER3R3A1ajJSQXNlYi9EYm5JdzZCZmtNTXc4dwpyOWI1dVJkTVZBUHdoMXpaRmRTSGhlcEJoYTZVQVVVMWZTaHVkZDRJcnBiVklaVmkxUjYwWmpaVElaNGVpME9LCmRSL2pxRXVCQWdNQkFBRUNnZ0VBTnNxL0FPVXJFSnlHSHk5Tm9ta1J2NHdpbFRHczZ1Q2Z5SVVyUWRQblU1K2gKUm42ejhhYTY1WktodXd0dHljdXlvbVVHMUdBc21WNkxHMktKd2hpdXhKK3NOTEprWVJBek5odFhDWGdaV0o5OQpabWlTeTFXV1N6dU9GL0JKNlZkeFZ5bGRFU24zTlcxZlBJNDdsb1BlRC9YQW96MlpiUmhRbE8vMFAvS280QncwClpWN1FNTUhxaFJoWmhLOGVNYWZmVDdUdjdzRGhyb2daTitXR3VFVUlRZTloWkk1NTRxaTZuWDdMTHJ2RURVRGsKZ2RFMURNWXhYVm1PM1lpWHRmanhnV1plSlU1empjZzhEOXErWVBPV3NEU3hPOVpzUmMzTjlKV1F2bDViemIwegp0MmxhMEhnRHNSZTVpUjBuSzdLRHlGVXZVZjNvMWF5M2YxYW5Rc1p6WlFLQmdRRGxHOURmSUtHVUlYMjlabHNMCkNaaVhtRWRENEJYRFZRS2xTR1VXTlVnak1zL1NrM3JkbStYd2ppeXE0b3BVNVI1a3hzZklrUW1DU0c5Rk5hMkYKa2NmQlpjZ0lHdXJzNC9IWGkyVzdEVWRYQnlHSHVWa0RPQzV2VTdOc0thNmx5dHlYTXZLRjBvT0Z3bnFmRlNwSwpySlZLMFB2WlRQQWJUUmFqSVc4akdSWW1sd0tCZ1FDN29EbW1lZnE2VVpaQXZqWVVvSU5YZmNWTEFBQUtPNmVNCkRYaE5qTEdaMVhQTFhla0d3b0ppOGlwS0pYMlpLSm9PTWlyaEFTK0plQzIzNEcvMXkza1Y4aW1jaU1kUDNNckUKSDliS0lSMytoYUh4SjJ0YVlVYnRSYkJQdDkzLzE1cXNLTGRiTGlhUGVLVFNxbVhnYVVGdEVqajJrdjVmZVFmMgp0V1dJYW42NXB3S0JnUUN6T2VOWDZXcjlPb1htMkY5NGJ2VlVBZWdlRFBwNVo5TStBVGd5KzFPSFZZU0dNcUQzCkk3SHBVUTlZVHdmd0NaeVJNWCt3UXVXeGFZRENINCt5NGF2bWV2elVlbG8xSHN4ZDFjcXJYV1Bsak1xS0psQ2YKMkI5Ykw1czRqaEwxMTVCaEo1WFpZaWxKUmk0dXJKdjg5cTJEYmFEWENQejhIbjRLOTJpOWlDNXYyUUtCZ0E4agpsb05BUkdMVVFuTm01YVkwYldTWjJWbDczb1QwMjBnSnJqTlRydURpd0QwZ2pyVGs3UEJlNmRxaHU4aW41Z1pQCk5mYUJ5ZndsbmtxLzZVakQ2amxER09od2dPU0l4RE9lL2czQkxsSmpKZlgzWUVvaW56NTE2UXdGb2Z3S3dZZ3kKb05qU21IbnJHaUdGYmtMMU96bzV4aTdmSFhkR3BNWGJUUjM4dWN6eEFvR0FkbUQyVFltSE1BUU5kNlJGYTd0dAp3NHBSRW5seWxTY3VPYXVkQ2h6enF0OERyb29EaWVENFhvTGQvdE1UcUlkYTNRQ05LM0ZVaWhXdUdyUEFKa01yCjZYcU96a3NCcnVRcDR4SmdjbWZSb016MGZTRG5sMHNSOFd3K3lMVWlrMVdzSlhMVUJVWnBpaDNlWmh4REw0NGwKaHI0L0lpTXdqVkZZcDE3VnVEZnk2Umc9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K",
			},
			expectedCfg: config.Config{},
			expectedErr: config.ErrEnvVarValueMissing{VarName: "HTTP_PORT"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Arrange
			for key, value := range tt.envVars {
				t.Setenv(key, value)
			}
			// Act
			cfg, err := config.LoadConfigFromEnvVars()
			// Assert
			assert.Error(t, err)
			assert.Equal(t, tt.expectedErr, err)
			assert.Equal(t, tt.expectedCfg, cfg)
			assert.Equal(t, "Missing environment variable: HTTP_PORT", err.Error())
		})
	}
}
