/* tslint:disable */
/* eslint-disable */
/**
 * VeterinaryStaff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateVeterinarianProfile
 */
export interface UpdateVeterinarianProfile {
  /**
   *
   * @type {string}
   * @memberof UpdateVeterinarianProfile
   */
  veterinarianId?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateVeterinarianProfile
   */
  specializations?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateVeterinarianProfile
   */
  phoneNumber?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateVeterinarianProfile
   */
  email?: string;
}

/**
 * Check if a given object implements the UpdateVeterinarianProfile interface.
 */
export function instanceOfUpdateVeterinarianProfile(
  value: object,
): value is UpdateVeterinarianProfile {
  return true;
}

export function UpdateVeterinarianProfileFromJSON(
  json: any,
): UpdateVeterinarianProfile {
  return UpdateVeterinarianProfileFromJSONTyped(json, false);
}

export function UpdateVeterinarianProfileFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateVeterinarianProfile {
  if (json == null) {
    return json;
  }
  return {
    veterinarianId:
      json["veterinarianId"] == null ? undefined : json["veterinarianId"],
    specializations:
      json["specializations"] == null ? undefined : json["specializations"],
    phoneNumber: json["phoneNumber"] == null ? undefined : json["phoneNumber"],
    email: json["email"] == null ? undefined : json["email"],
  };
}

export function UpdateVeterinarianProfileToJSON(
  json: any,
): UpdateVeterinarianProfile {
  return UpdateVeterinarianProfileToJSONTyped(json, false);
}

export function UpdateVeterinarianProfileToJSONTyped(
  value?: UpdateVeterinarianProfile | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    veterinarianId: value["veterinarianId"],
    specializations: value["specializations"],
    phoneNumber: value["phoneNumber"],
    email: value["email"],
  };
}
