// Package inbound provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package inbound

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Error defines model for Error.
type Error struct {
	Code    *int32  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// InsuranceClaim Represents an insurance claim submitted for a pet's veterinary services
type InsuranceClaim struct {
	ApprovedAmount *float32 `json:"approved_amount,omitempty"`
	ClaimAmount    *float32 `json:"claim_amount,omitempty"`
	ClaimId        *string  `json:"claim_id,omitempty"`
	InvoiceId      *string  `json:"invoice_id,omitempty"`
	Notes          *string  `json:"notes,omitempty"`
	OwnerId        *string  `json:"owner_id,omitempty"`
	PetId          *string  `json:"pet_id,omitempty"`
	PolicyNumber   *string  `json:"policy_number,omitempty"`
	ProviderId     *string  `json:"provider_id,omitempty"`
	ResolutionDate *string  `json:"resolution_date,omitempty"`
	Status         *string  `json:"status,omitempty"`
	SubmissionDate *string  `json:"submission_date,omitempty"`
}

// InsuranceProvider Represents a pet insurance company partnered with the clinic
type InsuranceProvider struct {
	ClaimSubmissionUrl *string `json:"claim_submission_url,omitempty"`
	ContactName        *string `json:"contact_name,omitempty"`
	Email              *string `json:"email,omitempty"`
	Name               *string `json:"name,omitempty"`
	PhoneNumber        *string `json:"phone_number,omitempty"`
	ProviderId         *string `json:"provider_id,omitempty"`
	Status             *string `json:"status,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /v1/insuranceclaims)
	FindAllInsuranceClaims(w http.ResponseWriter, r *http.Request)

	// (GET /v1/insuranceclaims/{insuranceClaimId})
	FindOneInsuranceClaim(w http.ResponseWriter, r *http.Request, insuranceClaimId string)

	// (GET /v1/insuranceproviders)
	FindAllInsuranceProviders(w http.ResponseWriter, r *http.Request)

	// (GET /v1/insuranceproviders/{insuranceProviderId})
	FindOneInsuranceProvider(w http.ResponseWriter, r *http.Request, insuranceProviderId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /v1/insuranceclaims)
func (_ Unimplemented) FindAllInsuranceClaims(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/insuranceclaims/{insuranceClaimId})
func (_ Unimplemented) FindOneInsuranceClaim(w http.ResponseWriter, r *http.Request, insuranceClaimId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/insuranceproviders)
func (_ Unimplemented) FindAllInsuranceProviders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/insuranceproviders/{insuranceProviderId})
func (_ Unimplemented) FindOneInsuranceProvider(w http.ResponseWriter, r *http.Request, insuranceProviderId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// FindAllInsuranceClaims operation middleware
func (siw *ServerInterfaceWrapper) FindAllInsuranceClaims(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindAllInsuranceClaims(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindOneInsuranceClaim operation middleware
func (siw *ServerInterfaceWrapper) FindOneInsuranceClaim(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "insuranceClaimId" -------------
	var insuranceClaimId string

	err = runtime.BindStyledParameterWithOptions("simple", "insuranceClaimId", chi.URLParam(r, "insuranceClaimId"), &insuranceClaimId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "insuranceClaimId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindOneInsuranceClaim(w, r, insuranceClaimId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindAllInsuranceProviders operation middleware
func (siw *ServerInterfaceWrapper) FindAllInsuranceProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindAllInsuranceProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindOneInsuranceProvider operation middleware
func (siw *ServerInterfaceWrapper) FindOneInsuranceProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "insuranceProviderId" -------------
	var insuranceProviderId string

	err = runtime.BindStyledParameterWithOptions("simple", "insuranceProviderId", chi.URLParam(r, "insuranceProviderId"), &insuranceProviderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "insuranceProviderId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindOneInsuranceProvider(w, r, insuranceProviderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/insuranceclaims", wrapper.FindAllInsuranceClaims)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/insuranceclaims/{insuranceClaimId}", wrapper.FindOneInsuranceClaim)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/insuranceproviders", wrapper.FindAllInsuranceProviders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/insuranceproviders/{insuranceProviderId}", wrapper.FindOneInsuranceProvider)
	})

	return r
}

type FindAllInsuranceClaimsRequestObject struct {
}

type FindAllInsuranceClaimsResponseObject interface {
	VisitFindAllInsuranceClaimsResponse(w http.ResponseWriter) error
}

type FindAllInsuranceClaims200JSONResponse []InsuranceClaim

func (response FindAllInsuranceClaims200JSONResponse) VisitFindAllInsuranceClaimsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FindAllInsuranceClaimsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FindAllInsuranceClaimsdefaultJSONResponse) VisitFindAllInsuranceClaimsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FindOneInsuranceClaimRequestObject struct {
	InsuranceClaimId string `json:"insuranceClaimId"`
}

type FindOneInsuranceClaimResponseObject interface {
	VisitFindOneInsuranceClaimResponse(w http.ResponseWriter) error
}

type FindOneInsuranceClaim200JSONResponse InsuranceClaim

func (response FindOneInsuranceClaim200JSONResponse) VisitFindOneInsuranceClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FindOneInsuranceClaimdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FindOneInsuranceClaimdefaultJSONResponse) VisitFindOneInsuranceClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FindAllInsuranceProvidersRequestObject struct {
}

type FindAllInsuranceProvidersResponseObject interface {
	VisitFindAllInsuranceProvidersResponse(w http.ResponseWriter) error
}

type FindAllInsuranceProviders200JSONResponse []InsuranceProvider

func (response FindAllInsuranceProviders200JSONResponse) VisitFindAllInsuranceProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FindAllInsuranceProvidersdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FindAllInsuranceProvidersdefaultJSONResponse) VisitFindAllInsuranceProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FindOneInsuranceProviderRequestObject struct {
	InsuranceProviderId string `json:"insuranceProviderId"`
}

type FindOneInsuranceProviderResponseObject interface {
	VisitFindOneInsuranceProviderResponse(w http.ResponseWriter) error
}

type FindOneInsuranceProvider200JSONResponse InsuranceProvider

func (response FindOneInsuranceProvider200JSONResponse) VisitFindOneInsuranceProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FindOneInsuranceProviderdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FindOneInsuranceProviderdefaultJSONResponse) VisitFindOneInsuranceProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /v1/insuranceclaims)
	FindAllInsuranceClaims(ctx context.Context, request FindAllInsuranceClaimsRequestObject) (FindAllInsuranceClaimsResponseObject, error)

	// (GET /v1/insuranceclaims/{insuranceClaimId})
	FindOneInsuranceClaim(ctx context.Context, request FindOneInsuranceClaimRequestObject) (FindOneInsuranceClaimResponseObject, error)

	// (GET /v1/insuranceproviders)
	FindAllInsuranceProviders(ctx context.Context, request FindAllInsuranceProvidersRequestObject) (FindAllInsuranceProvidersResponseObject, error)

	// (GET /v1/insuranceproviders/{insuranceProviderId})
	FindOneInsuranceProvider(ctx context.Context, request FindOneInsuranceProviderRequestObject) (FindOneInsuranceProviderResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// FindAllInsuranceClaims operation middleware
func (sh *strictHandler) FindAllInsuranceClaims(w http.ResponseWriter, r *http.Request) {
	var request FindAllInsuranceClaimsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FindAllInsuranceClaims(ctx, request.(FindAllInsuranceClaimsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindAllInsuranceClaims")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FindAllInsuranceClaimsResponseObject); ok {
		if err := validResponse.VisitFindAllInsuranceClaimsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FindOneInsuranceClaim operation middleware
func (sh *strictHandler) FindOneInsuranceClaim(w http.ResponseWriter, r *http.Request, insuranceClaimId string) {
	var request FindOneInsuranceClaimRequestObject

	request.InsuranceClaimId = insuranceClaimId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FindOneInsuranceClaim(ctx, request.(FindOneInsuranceClaimRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindOneInsuranceClaim")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FindOneInsuranceClaimResponseObject); ok {
		if err := validResponse.VisitFindOneInsuranceClaimResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FindAllInsuranceProviders operation middleware
func (sh *strictHandler) FindAllInsuranceProviders(w http.ResponseWriter, r *http.Request) {
	var request FindAllInsuranceProvidersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FindAllInsuranceProviders(ctx, request.(FindAllInsuranceProvidersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindAllInsuranceProviders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FindAllInsuranceProvidersResponseObject); ok {
		if err := validResponse.VisitFindAllInsuranceProvidersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FindOneInsuranceProvider operation middleware
func (sh *strictHandler) FindOneInsuranceProvider(w http.ResponseWriter, r *http.Request, insuranceProviderId string) {
	var request FindOneInsuranceProviderRequestObject

	request.InsuranceProviderId = insuranceProviderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FindOneInsuranceProvider(ctx, request.(FindOneInsuranceProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindOneInsuranceProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FindOneInsuranceProviderResponseObject); ok {
		if err := validResponse.VisitFindOneInsuranceProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWXYvbOhD9K0L3wn0x6+zum9/CpYU8delrWYIij5NZZEkdjb0Nwf+9SI7z6YRmF0qe",
	"4nhmrDPnzBl7I7WrvbNgOchiI4NeQa3S5RciR/HCk/NAjJBua1dC/K0c1YplIdHy85PMJK899H9hCSS7",
	"TNYQglqm7G0wMKFdyq7bpbvFG2iO2TMbGlJWw/9GYR2LSgia0DM6Kwv5HTxBiECFsgKHbKFjugjNokZm",
	"KEXlSCjhgf8LogUGQqtoLQJQixqCzE4aUt6Ta6Gcq9o1lo96q4xTvO/NNvWiby0d+oEKLEfYyCTa1qGG",
	"S2HruMd6FnHvFuhSmQe+GHIG9Xq+hTeaQa7F8vLDCYIzTdRmXiqG0ZzAiptx4EmvEK6UX52Rly2662MS",
	"p+BwUlztlV0Lr4gtEJTiHXkleBWHCC3qs9noRTvA2pAZbUc7y0rz3Kp6nAqoFY6XXizxK2fhMxJdpP+c",
	"2i4NYeVSMrKJsR3ZU1smTwYxfZnJTLZAoSf78WHyMElz6MEqj7KQz+lWJr3iVTo7bx/znQaJ0HR7Cck4",
	"kW0VpZuVspBf0ZZTY45XQbQsQfDOhl6Vp8mk30SWobef8t6gTs/J30KENqyyeIUM/Zn/ElSykP/k+6WX",
	"bzdefrJ+9hQpIrXuGTqetKkwGFi4SpziTamVagzfhPMavH4bj6BoLPzyoOPmgyGny8ZYzzd4hHNWdleF",
	"+GbhhJSoKqk6LtUgix8biRFBVFoOcyxPz0ji/WyQoJQFUwPZQcenc/n6SaVvEficyuMMUQIrNEEQMCG0",
	"UIrQaA0hVI0x67sTedgGf+6ul13FXzXYbnd/zGN71HerwIHTBrS3mG1H0E1+2590f5bbS37FdUPS3Rsv",
	"vlqB2kGU9E0gV8w+FHm+WbnAUZsujy/ETLaKUC1Mz+4Q7L9btk1I47QyMRQf/9r9DgAA///ZnOMUlQsA",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
