// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: postgres_queries.sql

package outbound

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addLoyaltyAccount = `-- name: AddLoyaltyAccount :exec
INSERT INTO ownermanagement.loyalty_accounts (
    loyalty_account_id,
    created_at,
    updated_at,
    deleted_at,
    deleted
    --,
    --loyalty_account_id
    --,
    --owner_id
    --,
    --points_balance
    --,
    --tier
    --,
    --enrolled_date
    --
    -- TODO
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
    -- TODO
)
`

type AddLoyaltyAccountParams struct {
	LoyaltyAccountID pgtype.UUID        `db:"loyalty_account_id" json:"loyalty_account_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Deleted          bool               `db:"deleted" json:"deleted"`
}

// AddLoyaltyAccount
//
//	INSERT INTO ownermanagement.loyalty_accounts (
//	    loyalty_account_id,
//	    created_at,
//	    updated_at,
//	    deleted_at,
//	    deleted
//	    --,
//	    --loyalty_account_id
//	    --,
//	    --owner_id
//	    --,
//	    --points_balance
//	    --,
//	    --tier
//	    --,
//	    --enrolled_date
//	    --
//	    -- TODO
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5
//	    -- TODO
//	)
func (q *Queries) AddLoyaltyAccount(ctx context.Context, arg AddLoyaltyAccountParams) error {
	_, err := q.db.Exec(ctx, addLoyaltyAccount,
		arg.LoyaltyAccountID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Deleted,
	)
	return err
}

const addOwner = `-- name: AddOwner :exec
INSERT INTO ownermanagement.owners (
    owner_id,
    created_at,
    updated_at,
    deleted_at,
    deleted
    --,
    --owner_id
    --,
    --first_name
    --,
    --last_name
    --,
    --email
    --,
    --phone_number
    --,
    --address
    --,
    --communication_preference
    --,
    --loyalty_member
    --,
    --loyalty_points
    --,
    --status
    --
    -- TODO
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
    -- TODO
)
`

type AddOwnerParams struct {
	OwnerID   pgtype.UUID        `db:"owner_id" json:"owner_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Deleted   bool               `db:"deleted" json:"deleted"`
}

// AddOwner
//
//	INSERT INTO ownermanagement.owners (
//	    owner_id,
//	    created_at,
//	    updated_at,
//	    deleted_at,
//	    deleted
//	    --,
//	    --owner_id
//	    --,
//	    --first_name
//	    --,
//	    --last_name
//	    --,
//	    --email
//	    --,
//	    --phone_number
//	    --,
//	    --address
//	    --,
//	    --communication_preference
//	    --,
//	    --loyalty_member
//	    --,
//	    --loyalty_points
//	    --,
//	    --status
//	    --
//	    -- TODO
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5
//	    -- TODO
//	)
func (q *Queries) AddOwner(ctx context.Context, arg AddOwnerParams) error {
	_, err := q.db.Exec(ctx, addOwner,
		arg.OwnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Deleted,
	)
	return err
}

const findAllLoyaltyAccounts = `-- name: FindAllLoyaltyAccounts :many
SELECT loyalty_account_id, created_at, updated_at, deleted_at, deleted FROM ownermanagement.loyalty_accounts
`

// FindAllLoyaltyAccounts
//
//	SELECT loyalty_account_id, created_at, updated_at, deleted_at, deleted FROM ownermanagement.loyalty_accounts
func (q *Queries) FindAllLoyaltyAccounts(ctx context.Context) ([]OwnermanagementLoyaltyAccount, error) {
	rows, err := q.db.Query(ctx, findAllLoyaltyAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnermanagementLoyaltyAccount
	for rows.Next() {
		var i OwnermanagementLoyaltyAccount
		if err := rows.Scan(
			&i.LoyaltyAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllOwners = `-- name: FindAllOwners :many
SELECT owner_id, created_at, updated_at, deleted_at, deleted FROM ownermanagement.owners
`

// FindAllOwners
//
//	SELECT owner_id, created_at, updated_at, deleted_at, deleted FROM ownermanagement.owners
func (q *Queries) FindAllOwners(ctx context.Context) ([]OwnermanagementOwner, error) {
	rows, err := q.db.Query(ctx, findAllOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnermanagementOwner
	for rows.Next() {
		var i OwnermanagementOwner
		if err := rows.Scan(
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneLoyaltyAccount = `-- name: FindOneLoyaltyAccount :one
SELECT loyalty_account_id, created_at, updated_at, deleted_at, deleted FROM ownermanagement.loyalty_accounts
WHERE loyalty_account_id = $1
`

type FindOneLoyaltyAccountParams struct {
	LoyaltyAccountID pgtype.UUID `db:"loyalty_account_id" json:"loyalty_account_id"`
}

// FindOneLoyaltyAccount
//
//	SELECT loyalty_account_id, created_at, updated_at, deleted_at, deleted FROM ownermanagement.loyalty_accounts
//	WHERE loyalty_account_id = $1
func (q *Queries) FindOneLoyaltyAccount(ctx context.Context, arg FindOneLoyaltyAccountParams) (OwnermanagementLoyaltyAccount, error) {
	row := q.db.QueryRow(ctx, findOneLoyaltyAccount, arg.LoyaltyAccountID)
	var i OwnermanagementLoyaltyAccount
	err := row.Scan(
		&i.LoyaltyAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Deleted,
	)
	return i, err
}

const findOneOwner = `-- name: FindOneOwner :one
SELECT owner_id, created_at, updated_at, deleted_at, deleted FROM ownermanagement.owners
WHERE owner_id = $1
`

type FindOneOwnerParams struct {
	OwnerID pgtype.UUID `db:"owner_id" json:"owner_id"`
}

// FindOneOwner
//
//	SELECT owner_id, created_at, updated_at, deleted_at, deleted FROM ownermanagement.owners
//	WHERE owner_id = $1
func (q *Queries) FindOneOwner(ctx context.Context, arg FindOneOwnerParams) (OwnermanagementOwner, error) {
	row := q.db.QueryRow(ctx, findOneOwner, arg.OwnerID)
	var i OwnermanagementOwner
	err := row.Scan(
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Deleted,
	)
	return i, err
}

const getLoyaltyAccount = `-- name: GetLoyaltyAccount :one
SELECT loyalty_account_id, created_at, updated_at, deleted_at, deleted FROM ownermanagement.loyalty_accounts
WHERE loyalty_account_id = $1
`

type GetLoyaltyAccountParams struct {
	LoyaltyAccountID pgtype.UUID `db:"loyalty_account_id" json:"loyalty_account_id"`
}

// GetLoyaltyAccount
//
//	SELECT loyalty_account_id, created_at, updated_at, deleted_at, deleted FROM ownermanagement.loyalty_accounts
//	WHERE loyalty_account_id = $1
func (q *Queries) GetLoyaltyAccount(ctx context.Context, arg GetLoyaltyAccountParams) (OwnermanagementLoyaltyAccount, error) {
	row := q.db.QueryRow(ctx, getLoyaltyAccount, arg.LoyaltyAccountID)
	var i OwnermanagementLoyaltyAccount
	err := row.Scan(
		&i.LoyaltyAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Deleted,
	)
	return i, err
}

const getOwner = `-- name: GetOwner :one
SELECT owner_id, created_at, updated_at, deleted_at, deleted FROM ownermanagement.owners
WHERE owner_id = $1
`

type GetOwnerParams struct {
	OwnerID pgtype.UUID `db:"owner_id" json:"owner_id"`
}

// GetOwner
//
//	SELECT owner_id, created_at, updated_at, deleted_at, deleted FROM ownermanagement.owners
//	WHERE owner_id = $1
func (q *Queries) GetOwner(ctx context.Context, arg GetOwnerParams) (OwnermanagementOwner, error) {
	row := q.db.QueryRow(ctx, getOwner, arg.OwnerID)
	var i OwnermanagementOwner
	err := row.Scan(
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Deleted,
	)
	return i, err
}

const updateLoyaltyAccount = `-- name: UpdateLoyaltyAccount :exec
UPDATE ownermanagement.loyalty_accounts
SET
    created_at = $2,
    updated_at = $3,
    deleted_at = $4,
    deleted = $5
    --,
    --loyalty_account_id
    --,
    --owner_id
    --,
    --points_balance
    --,
    --tier
    --,
    --enrolled_date
    --
    -- TODO
WHERE loyalty_account_id = $1
`

type UpdateLoyaltyAccountParams struct {
	LoyaltyAccountID pgtype.UUID        `db:"loyalty_account_id" json:"loyalty_account_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Deleted          bool               `db:"deleted" json:"deleted"`
}

// UpdateLoyaltyAccount
//
//	UPDATE ownermanagement.loyalty_accounts
//	SET
//	    created_at = $2,
//	    updated_at = $3,
//	    deleted_at = $4,
//	    deleted = $5
//	    --,
//	    --loyalty_account_id
//	    --,
//	    --owner_id
//	    --,
//	    --points_balance
//	    --,
//	    --tier
//	    --,
//	    --enrolled_date
//	    --
//	    -- TODO
//	WHERE loyalty_account_id = $1
func (q *Queries) UpdateLoyaltyAccount(ctx context.Context, arg UpdateLoyaltyAccountParams) error {
	_, err := q.db.Exec(ctx, updateLoyaltyAccount,
		arg.LoyaltyAccountID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Deleted,
	)
	return err
}

const updateOwner = `-- name: UpdateOwner :exec
UPDATE ownermanagement.owners
SET
    created_at = $2,
    updated_at = $3,
    deleted_at = $4,
    deleted = $5
    --,
    --owner_id
    --,
    --first_name
    --,
    --last_name
    --,
    --email
    --,
    --phone_number
    --,
    --address
    --,
    --communication_preference
    --,
    --loyalty_member
    --,
    --loyalty_points
    --,
    --status
    --
    -- TODO
WHERE owner_id = $1
`

type UpdateOwnerParams struct {
	OwnerID   pgtype.UUID        `db:"owner_id" json:"owner_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Deleted   bool               `db:"deleted" json:"deleted"`
}

// UpdateOwner
//
//	UPDATE ownermanagement.owners
//	SET
//	    created_at = $2,
//	    updated_at = $3,
//	    deleted_at = $4,
//	    deleted = $5
//	    --,
//	    --owner_id
//	    --,
//	    --first_name
//	    --,
//	    --last_name
//	    --,
//	    --email
//	    --,
//	    --phone_number
//	    --,
//	    --address
//	    --,
//	    --communication_preference
//	    --,
//	    --loyalty_member
//	    --,
//	    --loyalty_points
//	    --,
//	    --status
//	    --
//	    -- TODO
//	WHERE owner_id = $1
func (q *Queries) UpdateOwner(ctx context.Context, arg UpdateOwnerParams) error {
	_, err := q.db.Exec(ctx, updateOwner,
		arg.OwnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Deleted,
	)
	return err
}
