// Package inbound provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package inbound

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Error defines model for Error.
type Error struct {
	Code    *int32  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Invoice Represents a billing invoice for services rendered or products sold
type Invoice struct {
	AppointmentId  *string  `json:"appointment_id,omitempty"`
	DiscountAmount *float32 `json:"discount_amount,omitempty"`
	DueDate        *string  `json:"due_date,omitempty"`
	InvoiceId      *string  `json:"invoice_id,omitempty"`
	IssuedDate     *string  `json:"issued_date,omitempty"`
	LineItems      *string  `json:"line_items,omitempty"`
	OwnerId        *string  `json:"owner_id,omitempty"`
	PetId          *string  `json:"pet_id,omitempty"`
	Status         *string  `json:"status,omitempty"`
	Subtotal       *float32 `json:"subtotal,omitempty"`
	TaxAmount      *float32 `json:"tax_amount,omitempty"`
	TotalAmount    *float32 `json:"total_amount,omitempty"`
}

// Payment Represents a payment transaction against an invoice
type Payment struct {
	AmountPaid    *float32 `json:"amount_paid,omitempty"`
	InvoiceId     *string  `json:"invoice_id,omitempty"`
	OwnerId       *string  `json:"owner_id,omitempty"`
	PaymentDate   *string  `json:"payment_date,omitempty"`
	PaymentId     *string  `json:"payment_id,omitempty"`
	PaymentMethod *string  `json:"payment_method,omitempty"`
	Status        *string  `json:"status,omitempty"`
}

// Refund Represents a refund issued against a payment
type Refund struct {
	OwnerId      *string  `json:"owner_id,omitempty"`
	PaymentId    *string  `json:"payment_id,omitempty"`
	Reason       *string  `json:"reason,omitempty"`
	RefundAmount *float32 `json:"refund_amount,omitempty"`
	RefundDate   *string  `json:"refund_date,omitempty"`
	RefundId     *string  `json:"refund_id,omitempty"`
	Status       *string  `json:"status,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /v1/invoices)
	FindAllInvoices(w http.ResponseWriter, r *http.Request)

	// (GET /v1/invoices/{invoiceId})
	FindOneInvoice(w http.ResponseWriter, r *http.Request, invoiceId string)

	// (GET /v1/payments)
	FindAllPayments(w http.ResponseWriter, r *http.Request)

	// (GET /v1/payments/{paymentId})
	FindOnePayment(w http.ResponseWriter, r *http.Request, paymentId string)

	// (GET /v1/refunds)
	FindAllRefunds(w http.ResponseWriter, r *http.Request)

	// (GET /v1/refunds/{refundId})
	FindOneRefund(w http.ResponseWriter, r *http.Request, refundId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /v1/invoices)
func (_ Unimplemented) FindAllInvoices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/invoices/{invoiceId})
func (_ Unimplemented) FindOneInvoice(w http.ResponseWriter, r *http.Request, invoiceId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/payments)
func (_ Unimplemented) FindAllPayments(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/payments/{paymentId})
func (_ Unimplemented) FindOnePayment(w http.ResponseWriter, r *http.Request, paymentId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/refunds)
func (_ Unimplemented) FindAllRefunds(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/refunds/{refundId})
func (_ Unimplemented) FindOneRefund(w http.ResponseWriter, r *http.Request, refundId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// FindAllInvoices operation middleware
func (siw *ServerInterfaceWrapper) FindAllInvoices(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindAllInvoices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindOneInvoice operation middleware
func (siw *ServerInterfaceWrapper) FindOneInvoice(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "invoiceId" -------------
	var invoiceId string

	err = runtime.BindStyledParameterWithOptions("simple", "invoiceId", chi.URLParam(r, "invoiceId"), &invoiceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invoiceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindOneInvoice(w, r, invoiceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindAllPayments operation middleware
func (siw *ServerInterfaceWrapper) FindAllPayments(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindAllPayments(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindOnePayment operation middleware
func (siw *ServerInterfaceWrapper) FindOnePayment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "paymentId" -------------
	var paymentId string

	err = runtime.BindStyledParameterWithOptions("simple", "paymentId", chi.URLParam(r, "paymentId"), &paymentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paymentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindOnePayment(w, r, paymentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindAllRefunds operation middleware
func (siw *ServerInterfaceWrapper) FindAllRefunds(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindAllRefunds(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindOneRefund operation middleware
func (siw *ServerInterfaceWrapper) FindOneRefund(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "refundId" -------------
	var refundId string

	err = runtime.BindStyledParameterWithOptions("simple", "refundId", chi.URLParam(r, "refundId"), &refundId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refundId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindOneRefund(w, r, refundId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/invoices", wrapper.FindAllInvoices)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/invoices/{invoiceId}", wrapper.FindOneInvoice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/payments", wrapper.FindAllPayments)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/payments/{paymentId}", wrapper.FindOnePayment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/refunds", wrapper.FindAllRefunds)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/refunds/{refundId}", wrapper.FindOneRefund)
	})

	return r
}

type FindAllInvoicesRequestObject struct {
}

type FindAllInvoicesResponseObject interface {
	VisitFindAllInvoicesResponse(w http.ResponseWriter) error
}

type FindAllInvoices200JSONResponse []Invoice

func (response FindAllInvoices200JSONResponse) VisitFindAllInvoicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FindAllInvoicesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FindAllInvoicesdefaultJSONResponse) VisitFindAllInvoicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FindOneInvoiceRequestObject struct {
	InvoiceId string `json:"invoiceId"`
}

type FindOneInvoiceResponseObject interface {
	VisitFindOneInvoiceResponse(w http.ResponseWriter) error
}

type FindOneInvoice200JSONResponse Invoice

func (response FindOneInvoice200JSONResponse) VisitFindOneInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FindOneInvoicedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FindOneInvoicedefaultJSONResponse) VisitFindOneInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FindAllPaymentsRequestObject struct {
}

type FindAllPaymentsResponseObject interface {
	VisitFindAllPaymentsResponse(w http.ResponseWriter) error
}

type FindAllPayments200JSONResponse []Payment

func (response FindAllPayments200JSONResponse) VisitFindAllPaymentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FindAllPaymentsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FindAllPaymentsdefaultJSONResponse) VisitFindAllPaymentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FindOnePaymentRequestObject struct {
	PaymentId string `json:"paymentId"`
}

type FindOnePaymentResponseObject interface {
	VisitFindOnePaymentResponse(w http.ResponseWriter) error
}

type FindOnePayment200JSONResponse Payment

func (response FindOnePayment200JSONResponse) VisitFindOnePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FindOnePaymentdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FindOnePaymentdefaultJSONResponse) VisitFindOnePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FindAllRefundsRequestObject struct {
}

type FindAllRefundsResponseObject interface {
	VisitFindAllRefundsResponse(w http.ResponseWriter) error
}

type FindAllRefunds200JSONResponse []Refund

func (response FindAllRefunds200JSONResponse) VisitFindAllRefundsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FindAllRefundsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FindAllRefundsdefaultJSONResponse) VisitFindAllRefundsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FindOneRefundRequestObject struct {
	RefundId string `json:"refundId"`
}

type FindOneRefundResponseObject interface {
	VisitFindOneRefundResponse(w http.ResponseWriter) error
}

type FindOneRefund200JSONResponse Refund

func (response FindOneRefund200JSONResponse) VisitFindOneRefundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FindOneRefunddefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FindOneRefunddefaultJSONResponse) VisitFindOneRefundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /v1/invoices)
	FindAllInvoices(ctx context.Context, request FindAllInvoicesRequestObject) (FindAllInvoicesResponseObject, error)

	// (GET /v1/invoices/{invoiceId})
	FindOneInvoice(ctx context.Context, request FindOneInvoiceRequestObject) (FindOneInvoiceResponseObject, error)

	// (GET /v1/payments)
	FindAllPayments(ctx context.Context, request FindAllPaymentsRequestObject) (FindAllPaymentsResponseObject, error)

	// (GET /v1/payments/{paymentId})
	FindOnePayment(ctx context.Context, request FindOnePaymentRequestObject) (FindOnePaymentResponseObject, error)

	// (GET /v1/refunds)
	FindAllRefunds(ctx context.Context, request FindAllRefundsRequestObject) (FindAllRefundsResponseObject, error)

	// (GET /v1/refunds/{refundId})
	FindOneRefund(ctx context.Context, request FindOneRefundRequestObject) (FindOneRefundResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// FindAllInvoices operation middleware
func (sh *strictHandler) FindAllInvoices(w http.ResponseWriter, r *http.Request) {
	var request FindAllInvoicesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FindAllInvoices(ctx, request.(FindAllInvoicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindAllInvoices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FindAllInvoicesResponseObject); ok {
		if err := validResponse.VisitFindAllInvoicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FindOneInvoice operation middleware
func (sh *strictHandler) FindOneInvoice(w http.ResponseWriter, r *http.Request, invoiceId string) {
	var request FindOneInvoiceRequestObject

	request.InvoiceId = invoiceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FindOneInvoice(ctx, request.(FindOneInvoiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindOneInvoice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FindOneInvoiceResponseObject); ok {
		if err := validResponse.VisitFindOneInvoiceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FindAllPayments operation middleware
func (sh *strictHandler) FindAllPayments(w http.ResponseWriter, r *http.Request) {
	var request FindAllPaymentsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FindAllPayments(ctx, request.(FindAllPaymentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindAllPayments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FindAllPaymentsResponseObject); ok {
		if err := validResponse.VisitFindAllPaymentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FindOnePayment operation middleware
func (sh *strictHandler) FindOnePayment(w http.ResponseWriter, r *http.Request, paymentId string) {
	var request FindOnePaymentRequestObject

	request.PaymentId = paymentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FindOnePayment(ctx, request.(FindOnePaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindOnePayment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FindOnePaymentResponseObject); ok {
		if err := validResponse.VisitFindOnePaymentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FindAllRefunds operation middleware
func (sh *strictHandler) FindAllRefunds(w http.ResponseWriter, r *http.Request) {
	var request FindAllRefundsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FindAllRefunds(ctx, request.(FindAllRefundsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindAllRefunds")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FindAllRefundsResponseObject); ok {
		if err := validResponse.VisitFindAllRefundsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FindOneRefund operation middleware
func (sh *strictHandler) FindOneRefund(w http.ResponseWriter, r *http.Request, refundId string) {
	var request FindOneRefundRequestObject

	request.RefundId = refundId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FindOneRefund(ctx, request.(FindOneRefundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindOneRefund")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FindOneRefundResponseObject); ok {
		if err := validResponse.VisitFindOneRefundResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RWTY/jNgz9K4Lao7Ge3b35NgVaIKcO5losAsaiEy1kSaXodIPA/73Qh5POxhknWGCR",
	"nqKYTxT5yCfqKFvXe2fRcpDNUYZ2hz2k5e9EjuLCk/NIrDF9bp3C+Ns56oFlI7Xlz59kJfngMf/FLZIc",
	"K9ljCLBN6GIMTNpu5Tie4G7zFVuO6JXdO90mtMLQkvasnZWNfEVPGGKEAsRGG6PtVuiMFp0jEZD2usUg",
	"CK1CQiUcCU9ODS0HEZxRsvouC/Deacs9Wl5rNRNhJZUOrRssr6GPP29y7owDPudsh36TU1YDrhUwznos",
	"MV87UIcwoLq+3WiLa83Yh1mz+8ciXfPt8WqegYGHeZdh2LBjMLflzvDtLq6S6zt2zDXNCxxiDReaxmeU",
	"YAIboI0QAVvQNrAAO/XSZZOk0NYeMnPLGS0U+P0K5Rivl38CLOzvkXfuzkrPMfuK3WDVArGUQCJ37pnS",
	"ifALRm9i4IqZEEKMYNYUw7ir+cqWq2wXu/5hJsfUF51LYM0m2n7Ll9izVaV/g3h+WclK7pFCpvnjh6cP",
	"T6lpPFrwWjbyc/oUeeJdOrvef6xLy6X/W0zJR8IhVmulZCP/0FY9G7OacDG14J0Nec+np6d8q1suOgLv",
	"jW6Tg/prYTyPhbg63T+/Enaykb/U5wFSl+lRT1f5mQ0ggkMm4207PQujAwvXiVOECdPBYPiuyN4LKM+y",
	"meMHi988toxK4IQZqzfM1seyWqnxXZb/tLg63yRA0CMjBdn8dZQ6HhYLJytpoc+DsnhNJfl70IRKNkwD",
	"Vv/J6vv++vKD9bupbJc8FZNQyKBNnLRMGveoRBjaFkPoBmMOj1K6cpMsimJS308RxTSq7hLFKcIHY7Y+",
	"ltUNong5D4NFUZy8PowoTmW75KmY/ieiyBNtUROvBfYzJFHeGHcpYorvsVitj3lxgxxK0reoYfL5MGKY",
	"CnZJUbY8vBTi2w1pP3E+kJGN3DH70NT1cecCR+rHOr64KrkH0rAxmcfJmJ/EJQlpXAsmmqL7L+O/AQAA",
	"//9TdAocUA8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
