/* tslint:disable */
/* eslint-disable */
/**
 * NotificationsAndCommunications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CancelScheduledNotification
 */
export interface CancelScheduledNotification {
  /**
   *
   * @type {string}
   * @memberof CancelScheduledNotification
   */
  notificationId?: string;
}

/**
 * Check if a given object implements the CancelScheduledNotification interface.
 */
export function instanceOfCancelScheduledNotification(
  value: object,
): value is CancelScheduledNotification {
  return true;
}

export function CancelScheduledNotificationFromJSON(
  json: any,
): CancelScheduledNotification {
  return CancelScheduledNotificationFromJSONTyped(json, false);
}

export function CancelScheduledNotificationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CancelScheduledNotification {
  if (json == null) {
    return json;
  }
  return {
    notificationId:
      json["notificationId"] == null ? undefined : json["notificationId"],
  };
}

export function CancelScheduledNotificationToJSON(
  json: any,
): CancelScheduledNotification {
  return CancelScheduledNotificationToJSONTyped(json, false);
}

export function CancelScheduledNotificationToJSONTyped(
  value?: CancelScheduledNotification | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    notificationId: value["notificationId"],
  };
}
