/* tslint:disable */
/* eslint-disable */
/**
 * NotificationsAndCommunications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SendNotification
 */
export interface SendNotification {
  /**
   *
   * @type {string}
   * @memberof SendNotification
   */
  recipientId?: string;
  /**
   *
   * @type {string}
   * @memberof SendNotification
   */
  recipientType?: string;
  /**
   *
   * @type {string}
   * @memberof SendNotification
   */
  channel?: string;
  /**
   *
   * @type {string}
   * @memberof SendNotification
   */
  notificationType?: string;
  /**
   *
   * @type {string}
   * @memberof SendNotification
   */
  templateId?: string;
  /**
   *
   * @type {string}
   * @memberof SendNotification
   */
  messageBody?: string;
}

/**
 * Check if a given object implements the SendNotification interface.
 */
export function instanceOfSendNotification(
  value: object,
): value is SendNotification {
  return true;
}

export function SendNotificationFromJSON(json: any): SendNotification {
  return SendNotificationFromJSONTyped(json, false);
}

export function SendNotificationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SendNotification {
  if (json == null) {
    return json;
  }
  return {
    recipientId: json["recipientId"] == null ? undefined : json["recipientId"],
    recipientType:
      json["recipientType"] == null ? undefined : json["recipientType"],
    channel: json["channel"] == null ? undefined : json["channel"],
    notificationType:
      json["notificationType"] == null ? undefined : json["notificationType"],
    templateId: json["templateId"] == null ? undefined : json["templateId"],
    messageBody: json["messageBody"] == null ? undefined : json["messageBody"],
  };
}

export function SendNotificationToJSON(json: any): SendNotification {
  return SendNotificationToJSONTyped(json, false);
}

export function SendNotificationToJSONTyped(
  value?: SendNotification | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    recipientId: value["recipientId"],
    recipientType: value["recipientType"],
    channel: value["channel"],
    notificationType: value["notificationType"],
    templateId: value["templateId"],
    messageBody: value["messageBody"],
  };
}
