// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Api_keyScopes    = "api_key.Scopes"
	Basic_authScopes = "basic_auth.Scopes"
)

// Defines values for QuestionType.
const (
	Essay          QuestionType = "essay"
	MultipleChoice QuestionType = "multiple-choice"
	ShortAnswer    QuestionType = "short-answer"
)

// Exam defines model for Exam.
type Exam struct {
	// GradeLevel The grade level for which the exam is intended
	GradeLevel *int    `json:"gradeLevel,omitempty"`
	Id         *string `json:"id,omitempty"`

	// Name The name of the Exam
	Name      *string         `json:"name,omitempty"`
	Questions *[]ExamQuestion `json:"questions,omitempty"`
}

// ExamMetadata An Exam entity containing exam metadata
type ExamMetadata struct {
	// GradeLevel The grade level for which the exam is intended
	GradeLevel *int    `json:"gradeLevel,omitempty"`
	Id         *string `json:"id,omitempty"`

	// Name The name of the Exam
	Name *string `json:"name,omitempty"`
}

// ExamQuestion A question within an Exam, including the question text, possible answers, and the correct answer.
type ExamQuestion struct {
	// CorrectAnswer The correct answer to the question
	CorrectAnswer *string `json:"correctAnswer,omitempty"`

	// Index The index of the question in the exam
	Index *int `json:"index,omitempty"`

	// PossibleAnswers A list of possible answers for the question
	PossibleAnswers *[]string `json:"possibleAnswers,omitempty"`

	// PossiblePoints The points possible for answering the question correctly
	PossiblePoints *int `json:"possiblePoints,omitempty"`

	// QuestionText The text of the question
	QuestionText *string `json:"questionText,omitempty"`

	// QuestionType The type of question (e.g., multiple-choice, true/false).
	QuestionType *QuestionType `json:"questionType,omitempty"`
}

// Exams A list of Exam entities.
type Exams = []ExamMetadata

// QuestionType The type of question (e.g., multiple-choice, true/false).
type QuestionType string

// PostAddExamToLibraryJSONRequestBody defines body for PostAddExamToLibrary for application/json ContentType.
type PostAddExamToLibraryJSONRequestBody = Exam

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all Exams
	// (GET /exams)
	GetFindAllExams(w http.ResponseWriter, r *http.Request)
	// Add a new Exam to the Library
	// (POST /exams)
	PostAddExamToLibrary(w http.ResponseWriter, r *http.Request)
	// Get an Exam by ID
	// (GET /exams/{examID})
	GetFindOneByID(w http.ResponseWriter, r *http.Request, examID openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get all Exams
// (GET /exams)
func (_ Unimplemented) GetFindAllExams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new Exam to the Library
// (POST /exams)
func (_ Unimplemented) PostAddExamToLibrary(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get an Exam by ID
// (GET /exams/{examID})
func (_ Unimplemented) GetFindOneByID(w http.ResponseWriter, r *http.Request, examID openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetFindAllExams operation middleware
func (siw *ServerInterfaceWrapper) GetFindAllExams(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFindAllExams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAddExamToLibrary operation middleware
func (siw *ServerInterfaceWrapper) PostAddExamToLibrary(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAddExamToLibrary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFindOneByID operation middleware
func (siw *ServerInterfaceWrapper) GetFindOneByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "examID" -------------
	var examID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "examID", chi.URLParam(r, "examID"), &examID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "examID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Api_keyScopes, []string{})

	ctx = context.WithValue(ctx, Basic_authScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFindOneByID(w, r, examID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/exams", wrapper.GetFindAllExams)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/exams", wrapper.PostAddExamToLibrary)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/exams/{examID}", wrapper.GetFindOneByID)
	})

	return r
}

type GetFindAllExamsRequestObject struct {
}

type GetFindAllExamsResponseObject interface {
	VisitGetFindAllExamsResponse(w http.ResponseWriter) error
}

type GetFindAllExams200ResponseHeaders struct {
	XRequestId string
}

type GetFindAllExams200JSONResponse struct {
	Body    Exams
	Headers GetFindAllExams200ResponseHeaders
}

func (response GetFindAllExams200JSONResponse) VisitGetFindAllExamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetFindAllExams400Response struct {
}

func (response GetFindAllExams400Response) VisitGetFindAllExamsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetFindAllExamsdefaultResponse struct {
	StatusCode int
}

func (response GetFindAllExamsdefaultResponse) VisitGetFindAllExamsResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type PostAddExamToLibraryRequestObject struct {
	Body *PostAddExamToLibraryJSONRequestBody
}

type PostAddExamToLibraryResponseObject interface {
	VisitPostAddExamToLibraryResponse(w http.ResponseWriter) error
}

type PostAddExamToLibrary200ResponseHeaders struct {
	XRequestId string
}

type PostAddExamToLibrary200JSONResponse struct {
	Body    Exam
	Headers PostAddExamToLibrary200ResponseHeaders
}

func (response PostAddExamToLibrary200JSONResponse) VisitPostAddExamToLibraryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostAddExamToLibrary400Response struct {
}

func (response PostAddExamToLibrary400Response) VisitPostAddExamToLibraryResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostAddExamToLibrarydefaultResponse struct {
	StatusCode int
}

func (response PostAddExamToLibrarydefaultResponse) VisitPostAddExamToLibraryResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type GetFindOneByIDRequestObject struct {
	ExamID openapi_types.UUID `json:"examID"`
}

type GetFindOneByIDResponseObject interface {
	VisitGetFindOneByIDResponse(w http.ResponseWriter) error
}

type GetFindOneByID200ResponseHeaders struct {
	XRequestId string
}

type GetFindOneByID200JSONResponse struct {
	Body    Exam
	Headers GetFindOneByID200ResponseHeaders
}

func (response GetFindOneByID200JSONResponse) VisitGetFindOneByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetFindOneByID400Response struct {
}

func (response GetFindOneByID400Response) VisitGetFindOneByIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetFindOneByIDdefaultResponse struct {
	StatusCode int
}

func (response GetFindOneByIDdefaultResponse) VisitGetFindOneByIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get all Exams
	// (GET /exams)
	GetFindAllExams(ctx context.Context, request GetFindAllExamsRequestObject) (GetFindAllExamsResponseObject, error)
	// Add a new Exam to the Library
	// (POST /exams)
	PostAddExamToLibrary(ctx context.Context, request PostAddExamToLibraryRequestObject) (PostAddExamToLibraryResponseObject, error)
	// Get an Exam by ID
	// (GET /exams/{examID})
	GetFindOneByID(ctx context.Context, request GetFindOneByIDRequestObject) (GetFindOneByIDResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetFindAllExams operation middleware
func (sh *strictHandler) GetFindAllExams(w http.ResponseWriter, r *http.Request) {
	var request GetFindAllExamsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFindAllExams(ctx, request.(GetFindAllExamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFindAllExams")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFindAllExamsResponseObject); ok {
		if err := validResponse.VisitGetFindAllExamsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAddExamToLibrary operation middleware
func (sh *strictHandler) PostAddExamToLibrary(w http.ResponseWriter, r *http.Request) {
	var request PostAddExamToLibraryRequestObject

	var body PostAddExamToLibraryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAddExamToLibrary(ctx, request.(PostAddExamToLibraryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAddExamToLibrary")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAddExamToLibraryResponseObject); ok {
		if err := validResponse.VisitPostAddExamToLibraryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFindOneByID operation middleware
func (sh *strictHandler) GetFindOneByID(w http.ResponseWriter, r *http.Request, examID openapi_types.UUID) {
	var request GetFindOneByIDRequestObject

	request.ExamID = examID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFindOneByID(ctx, request.(GetFindOneByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFindOneByID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFindOneByIDResponseObject); ok {
		if err := validResponse.VisitGetFindOneByIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXT4/bthP9KgR/v0MLyJY3cYKtLsWmaYtFU+RPU7RAYARjcWxNQpEKSXnXMPTdi6Fk",
	"2bKUZA/toUBPlsXh8M17j0PqIHNbVtagCV5mB1kgKHTx8c/ZG/xUow+zW8X/fV5gCfyk0OeOqkDWyEy+",
	"LVDUhj7VKEihCbQhdGJjnQgFCtfmmMtEhn2FMpM+ODJb2TRN0uWMy/14DyX/gtYvNzJ7d5D/d7iRmfxf",
	"eoKYdhNSjv4VAygIIJvkICtnK3SBMCaLa5I18Q8FLOPD1xK+7mbJpgcLzsFeNqcXdv0B8yCbVXJBw40R",
	"nEMwA2EvyOS6VmS2goIX4L3NCQIq0UOb8zKDOkbUXuTMrQlAhpMivy6PE5OL8rcOFL7AHeppueK40BwQ",
	"hborKC+iXDEveUEmoFGoZCL5VaVRZleLngUe3qLjCiiaow+Sy+/gqXq6XM4eL9WT2TJ/pGbXsM5n1xsF",
	"13B1tVyr5dgMiTRQ4jRaHhF2E/FFl5xhkr/Fh+P7S4uNZGsZ74UeM97rI+4oFGQEtBokZ4oykD4s4H1I",
	"RGW9p7VGAcbfofOJAKNiYG6dwzx0A/ORVt34TRyeJmCYQgQ7QDCgQ9ntFLlkFN5PJ49DR3r7qsj0dhhY",
	"YMoBx9rbEvwUqZp84DUuaerbxFQx77pqcggykWty7MYN+UKuktOmHtU63LkneK8sdU1uTEIVx07wGFYL",
	"caR3J4ben0N9MsXLccpbvA/Ty7J3LqkfyPlHASw7laB5V3409s6w/mtwH7+fErpfMw58ueW9Po/97F75",
	"op6n7kTo2dsP7rVnzXuk2OuLIiaI21exJfSqfIPz7TwRZa0DVRpneWEpx0QEV2O6Ae3xW4aHpi7ZWBdx",
	"MpG+sC7MWs050HvYs88mDi0yGxudRyGKFEl4QWsHjk2xQ+dbpFfzxXzBBdkKDVQkM/l4vpg/4h4AoYg8",
	"pXjkeIsTLnmDwRHuUIDWopUjpnPAAXwwy58x/ERG3Wh9HHfoK2t8218eLRZtm+GOHleAqtKUxwTpB992",
	"wdPh/jXhfEvCEObLX2TypbvDVNIuPB3ExtzLFvJwiVuzA01KkKnqaE6FG6j1BGe/G7yvMOfDFp2zLnrb",
	"12XJ+kS+BmwG2Hr2BAuhOxVXbd+YSP6DQwgoQBi8a+3P50TcwZWzO1KohMIApMdKvbI+3CjFs97ak2G6",
	"K9Izq/Z/q1JTQkXEwQpQ6niO6AEQcqhkxtum+YeN9G/30Y1S5zbo2DzJOu2rJum2fHrgn9vnzQP2vvBk",
	"tt0tR6z38Up5+/xzneClwWf7OFyBgxJDJPPdVB+9fX5+seIaXLco93KO4kYlj7cz2UIeWSU5k31jXQlB",
	"ZrKuSU1cyVb/2WrKVpjXjsI+6gQVvf+I/LziT5s1eMrfQx2K+GY1amamN0bU5jPGi6u43dEMtdMyk0UI",
	"VZam2uagC+tDdr24XqRQUXo2O91dxW+s0xT/sDmrHsxhqg91oaJ3sR867Qi+WTV/BQAA//+xYNLwqA4A",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
