openapi: "3.0.0"
info:
  version: 1.0.0
  title: Reporting API
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
paths:
  # /v1/reports:
  #   get:
  #     operationId: getAvailableReports
  #     responses:
  #       '200':
  #         description: A list of reports available for reporting
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 $ref: '#/components/schemas/Report'
  #       default:
  #         description: unexpected error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'

  # /v1/reports/{reportName}:
  #   get:
  #     operationId: getReport
  #     parameters:
  #       - name: reportName
  #         in: path
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: Report retrieved successfully
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Report'
  #       default:
  #         description: unexpected error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'
  /v1/metrics/{metricName}:
    get:
      operationId: getMetric
      parameters:
        - name: metricName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Metric retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metric'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:

    Metric:
      type: object
      required:
        - metricName
      properties:
        metricName:
          type: string
        metricValue:
          type: number
          format: double

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string