// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: postgres_queries.sql

package outbound

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addExam = `-- name: AddExam :exec
INSERT INTO examination.exams (
    exam_id,
    created_at,
    updated_at,
    deleted_at,
    deleted,
    student_id,
    completed,
    completed_at,
    started_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type AddExamParams struct {
	ExamID      pgtype.UUID        `db:"exam_id" json:"exam_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Deleted     bool               `db:"deleted" json:"deleted"`
	StudentID   pgtype.UUID        `db:"student_id" json:"student_id"`
	Completed   bool               `db:"completed" json:"completed"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
}

// AddExam
//
//	INSERT INTO examination.exams (
//	    exam_id,
//	    created_at,
//	    updated_at,
//	    deleted_at,
//	    deleted,
//	    student_id,
//	    completed,
//	    completed_at,
//	    started_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9
//	)
func (q *Queries) AddExam(ctx context.Context, arg AddExamParams) error {
	_, err := q.db.Exec(ctx, addExam,
		arg.ExamID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Deleted,
		arg.StudentID,
		arg.Completed,
		arg.CompletedAt,
		arg.StartedAt,
	)
	return err
}

const findAllExams = `-- name: FindAllExams :many
SELECT exam_id, created_at, updated_at, deleted_at, deleted, student_id, completed, completed_at, started_at FROM examination.exams
`

// FindAllExams
//
//	SELECT exam_id, created_at, updated_at, deleted_at, deleted, student_id, completed, completed_at, started_at FROM examination.exams
func (q *Queries) FindAllExams(ctx context.Context) ([]ExaminationExam, error) {
	rows, err := q.db.Query(ctx, findAllExams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExaminationExam
	for rows.Next() {
		var i ExaminationExam
		if err := rows.Scan(
			&i.ExamID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Deleted,
			&i.StudentID,
			&i.Completed,
			&i.CompletedAt,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
