// Package api_client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api_client

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	Code    *int32  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// MedicalRecord Represents the medical history and records for a pet
type MedicalRecord struct {
	Diagnosis        *string `json:"diagnosis,omitempty"`
	FollowUpRequired *bool   `json:"follow_up_required,omitempty"`
	MedicalRecordId  *string `json:"medical_record_id,omitempty"`
	Notes            *string `json:"notes,omitempty"`
	PetId            *string `json:"pet_id,omitempty"`
	Treatment        *string `json:"treatment,omitempty"`
	VeterinarianId   *string `json:"veterinarian_id,omitempty"`
	VisitDate        *string `json:"visit_date,omitempty"`
}

// Pet Represents a pet patient registered at the clinic
type Pet struct {
	Breed           *string  `json:"breed,omitempty"`
	DateOfBirth     *string  `json:"date_of_birth,omitempty"`
	Gender          *string  `json:"gender,omitempty"`
	MicrochipNumber *string  `json:"microchip_number,omitempty"`
	Name            *string  `json:"name,omitempty"`
	OwnerId         *string  `json:"owner_id,omitempty"`
	PetId           *string  `json:"pet_id,omitempty"`
	Species         *string  `json:"species,omitempty"`
	Status          *string  `json:"status,omitempty"`
	Weight          *float32 `json:"weight,omitempty"`
}

// VaccinationRecord Represents a vaccination record for a pet
type VaccinationRecord struct {
	AdministeredBy   *string `json:"administered_by,omitempty"`
	AdministeredDate *string `json:"administered_date,omitempty"`
	ExpiryDate       *string `json:"expiry_date,omitempty"`
	PetId            *string `json:"pet_id,omitempty"`
	VaccinationId    *string `json:"vaccination_id,omitempty"`
	VaccineName      *string `json:"vaccine_name,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// FindAllMedicalRecords request
	FindAllMedicalRecords(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindOneMedicalRecord request
	FindOneMedicalRecord(ctx context.Context, medicalRecordId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindAllPets request
	FindAllPets(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindOnePet request
	FindOnePet(ctx context.Context, petId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindAllVaccinationRecords request
	FindAllVaccinationRecords(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindOneVaccinationRecord request
	FindOneVaccinationRecord(ctx context.Context, vaccinationRecordId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) FindAllMedicalRecords(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindAllMedicalRecordsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindOneMedicalRecord(ctx context.Context, medicalRecordId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindOneMedicalRecordRequest(c.Server, medicalRecordId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindAllPets(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindAllPetsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindOnePet(ctx context.Context, petId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindOnePetRequest(c.Server, petId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindAllVaccinationRecords(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindAllVaccinationRecordsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindOneVaccinationRecord(ctx context.Context, vaccinationRecordId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindOneVaccinationRecordRequest(c.Server, vaccinationRecordId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewFindAllMedicalRecordsRequest generates requests for FindAllMedicalRecords
func NewFindAllMedicalRecordsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/medicalrecords")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindOneMedicalRecordRequest generates requests for FindOneMedicalRecord
func NewFindOneMedicalRecordRequest(server string, medicalRecordId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "medicalRecordId", runtime.ParamLocationPath, medicalRecordId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/medicalrecords/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindAllPetsRequest generates requests for FindAllPets
func NewFindAllPetsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/pets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindOnePetRequest generates requests for FindOnePet
func NewFindOnePetRequest(server string, petId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "petId", runtime.ParamLocationPath, petId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/pets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindAllVaccinationRecordsRequest generates requests for FindAllVaccinationRecords
func NewFindAllVaccinationRecordsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/vaccinationrecords")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindOneVaccinationRecordRequest generates requests for FindOneVaccinationRecord
func NewFindOneVaccinationRecordRequest(server string, vaccinationRecordId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "vaccinationRecordId", runtime.ParamLocationPath, vaccinationRecordId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/vaccinationrecords/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// FindAllMedicalRecordsWithResponse request
	FindAllMedicalRecordsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllMedicalRecordsResponse, error)

	// FindOneMedicalRecordWithResponse request
	FindOneMedicalRecordWithResponse(ctx context.Context, medicalRecordId string, reqEditors ...RequestEditorFn) (*FindOneMedicalRecordResponse, error)

	// FindAllPetsWithResponse request
	FindAllPetsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllPetsResponse, error)

	// FindOnePetWithResponse request
	FindOnePetWithResponse(ctx context.Context, petId string, reqEditors ...RequestEditorFn) (*FindOnePetResponse, error)

	// FindAllVaccinationRecordsWithResponse request
	FindAllVaccinationRecordsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllVaccinationRecordsResponse, error)

	// FindOneVaccinationRecordWithResponse request
	FindOneVaccinationRecordWithResponse(ctx context.Context, vaccinationRecordId string, reqEditors ...RequestEditorFn) (*FindOneVaccinationRecordResponse, error)
}

type FindAllMedicalRecordsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]MedicalRecord
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindAllMedicalRecordsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindAllMedicalRecordsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindOneMedicalRecordResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MedicalRecord
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindOneMedicalRecordResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindOneMedicalRecordResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindAllPetsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Pet
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindAllPetsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindAllPetsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindOnePetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Pet
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindOnePetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindOnePetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindAllVaccinationRecordsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]VaccinationRecord
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindAllVaccinationRecordsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindAllVaccinationRecordsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindOneVaccinationRecordResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VaccinationRecord
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindOneVaccinationRecordResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindOneVaccinationRecordResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// FindAllMedicalRecordsWithResponse request returning *FindAllMedicalRecordsResponse
func (c *ClientWithResponses) FindAllMedicalRecordsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllMedicalRecordsResponse, error) {
	rsp, err := c.FindAllMedicalRecords(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindAllMedicalRecordsResponse(rsp)
}

// FindOneMedicalRecordWithResponse request returning *FindOneMedicalRecordResponse
func (c *ClientWithResponses) FindOneMedicalRecordWithResponse(ctx context.Context, medicalRecordId string, reqEditors ...RequestEditorFn) (*FindOneMedicalRecordResponse, error) {
	rsp, err := c.FindOneMedicalRecord(ctx, medicalRecordId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindOneMedicalRecordResponse(rsp)
}

// FindAllPetsWithResponse request returning *FindAllPetsResponse
func (c *ClientWithResponses) FindAllPetsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllPetsResponse, error) {
	rsp, err := c.FindAllPets(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindAllPetsResponse(rsp)
}

// FindOnePetWithResponse request returning *FindOnePetResponse
func (c *ClientWithResponses) FindOnePetWithResponse(ctx context.Context, petId string, reqEditors ...RequestEditorFn) (*FindOnePetResponse, error) {
	rsp, err := c.FindOnePet(ctx, petId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindOnePetResponse(rsp)
}

// FindAllVaccinationRecordsWithResponse request returning *FindAllVaccinationRecordsResponse
func (c *ClientWithResponses) FindAllVaccinationRecordsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllVaccinationRecordsResponse, error) {
	rsp, err := c.FindAllVaccinationRecords(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindAllVaccinationRecordsResponse(rsp)
}

// FindOneVaccinationRecordWithResponse request returning *FindOneVaccinationRecordResponse
func (c *ClientWithResponses) FindOneVaccinationRecordWithResponse(ctx context.Context, vaccinationRecordId string, reqEditors ...RequestEditorFn) (*FindOneVaccinationRecordResponse, error) {
	rsp, err := c.FindOneVaccinationRecord(ctx, vaccinationRecordId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindOneVaccinationRecordResponse(rsp)
}

// ParseFindAllMedicalRecordsResponse parses an HTTP response from a FindAllMedicalRecordsWithResponse call
func ParseFindAllMedicalRecordsResponse(rsp *http.Response) (*FindAllMedicalRecordsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindAllMedicalRecordsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []MedicalRecord
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindOneMedicalRecordResponse parses an HTTP response from a FindOneMedicalRecordWithResponse call
func ParseFindOneMedicalRecordResponse(rsp *http.Response) (*FindOneMedicalRecordResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindOneMedicalRecordResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MedicalRecord
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindAllPetsResponse parses an HTTP response from a FindAllPetsWithResponse call
func ParseFindAllPetsResponse(rsp *http.Response) (*FindAllPetsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindAllPetsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Pet
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindOnePetResponse parses an HTTP response from a FindOnePetWithResponse call
func ParseFindOnePetResponse(rsp *http.Response) (*FindOnePetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindOnePetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Pet
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindAllVaccinationRecordsResponse parses an HTTP response from a FindAllVaccinationRecordsWithResponse call
func ParseFindAllVaccinationRecordsResponse(rsp *http.Response) (*FindAllVaccinationRecordsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindAllVaccinationRecordsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []VaccinationRecord
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindOneVaccinationRecordResponse parses an HTTP response from a FindOneVaccinationRecordWithResponse call
func ParseFindOneVaccinationRecordResponse(rsp *http.Response) (*FindOneVaccinationRecordResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindOneVaccinationRecordResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VaccinationRecord
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
