// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: postgres_queries.sql

package outbound

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addInsuranceClaim = `-- name: AddInsuranceClaim :exec
INSERT INTO insuranceandclaims.insurance_claims (
    insurance_claim_id,
    created_at,
    updated_at,
    deleted_at,
    deleted
    --,
    --claim_id
    --,
    --owner_id
    --,
    --pet_id
    --,
    --provider_id
    --,
    --invoice_id
    --,
    --policy_number
    --,
    --claim_amount
    --,
    --approved_amount
    --,
    --submission_date
    --,
    --resolution_date
    --,
    --status
    --,
    --notes
    --
    -- TODO
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
    -- TODO
)
`

type AddInsuranceClaimParams struct {
	InsuranceClaimID pgtype.UUID        `db:"insurance_claim_id" json:"insurance_claim_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Deleted          bool               `db:"deleted" json:"deleted"`
}

// AddInsuranceClaim
//
//	INSERT INTO insuranceandclaims.insurance_claims (
//	    insurance_claim_id,
//	    created_at,
//	    updated_at,
//	    deleted_at,
//	    deleted
//	    --,
//	    --claim_id
//	    --,
//	    --owner_id
//	    --,
//	    --pet_id
//	    --,
//	    --provider_id
//	    --,
//	    --invoice_id
//	    --,
//	    --policy_number
//	    --,
//	    --claim_amount
//	    --,
//	    --approved_amount
//	    --,
//	    --submission_date
//	    --,
//	    --resolution_date
//	    --,
//	    --status
//	    --,
//	    --notes
//	    --
//	    -- TODO
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5
//	    -- TODO
//	)
func (q *Queries) AddInsuranceClaim(ctx context.Context, arg AddInsuranceClaimParams) error {
	_, err := q.db.Exec(ctx, addInsuranceClaim,
		arg.InsuranceClaimID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Deleted,
	)
	return err
}

const addInsuranceProvider = `-- name: AddInsuranceProvider :exec
INSERT INTO insuranceandclaims.insurance_providers (
    insurance_provider_id,
    created_at,
    updated_at,
    deleted_at,
    deleted
    --,
    --provider_id
    --,
    --name
    --,
    --contact_name
    --,
    --email
    --,
    --phone_number
    --,
    --claim_submission_url
    --,
    --status
    --
    -- TODO
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
    -- TODO
)
`

type AddInsuranceProviderParams struct {
	InsuranceProviderID pgtype.UUID        `db:"insurance_provider_id" json:"insurance_provider_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Deleted             bool               `db:"deleted" json:"deleted"`
}

// AddInsuranceProvider
//
//	INSERT INTO insuranceandclaims.insurance_providers (
//	    insurance_provider_id,
//	    created_at,
//	    updated_at,
//	    deleted_at,
//	    deleted
//	    --,
//	    --provider_id
//	    --,
//	    --name
//	    --,
//	    --contact_name
//	    --,
//	    --email
//	    --,
//	    --phone_number
//	    --,
//	    --claim_submission_url
//	    --,
//	    --status
//	    --
//	    -- TODO
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5
//	    -- TODO
//	)
func (q *Queries) AddInsuranceProvider(ctx context.Context, arg AddInsuranceProviderParams) error {
	_, err := q.db.Exec(ctx, addInsuranceProvider,
		arg.InsuranceProviderID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Deleted,
	)
	return err
}

const findAllInsuranceClaims = `-- name: FindAllInsuranceClaims :many
SELECT insurance_claim_id, created_at, updated_at, deleted_at, deleted FROM insuranceandclaims.insurance_claims
`

// FindAllInsuranceClaims
//
//	SELECT insurance_claim_id, created_at, updated_at, deleted_at, deleted FROM insuranceandclaims.insurance_claims
func (q *Queries) FindAllInsuranceClaims(ctx context.Context) ([]InsuranceandclaimsInsuranceClaim, error) {
	rows, err := q.db.Query(ctx, findAllInsuranceClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsuranceandclaimsInsuranceClaim
	for rows.Next() {
		var i InsuranceandclaimsInsuranceClaim
		if err := rows.Scan(
			&i.InsuranceClaimID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllInsuranceProviders = `-- name: FindAllInsuranceProviders :many
SELECT insurance_provider_id, created_at, updated_at, deleted_at, deleted FROM insuranceandclaims.insurance_providers
`

// FindAllInsuranceProviders
//
//	SELECT insurance_provider_id, created_at, updated_at, deleted_at, deleted FROM insuranceandclaims.insurance_providers
func (q *Queries) FindAllInsuranceProviders(ctx context.Context) ([]InsuranceandclaimsInsuranceProvider, error) {
	rows, err := q.db.Query(ctx, findAllInsuranceProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsuranceandclaimsInsuranceProvider
	for rows.Next() {
		var i InsuranceandclaimsInsuranceProvider
		if err := rows.Scan(
			&i.InsuranceProviderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneInsuranceClaim = `-- name: FindOneInsuranceClaim :one
SELECT insurance_claim_id, created_at, updated_at, deleted_at, deleted FROM insuranceandclaims.insurance_claims
WHERE insurance_claim_id = $1
`

type FindOneInsuranceClaimParams struct {
	InsuranceClaimID pgtype.UUID `db:"insurance_claim_id" json:"insurance_claim_id"`
}

// FindOneInsuranceClaim
//
//	SELECT insurance_claim_id, created_at, updated_at, deleted_at, deleted FROM insuranceandclaims.insurance_claims
//	WHERE insurance_claim_id = $1
func (q *Queries) FindOneInsuranceClaim(ctx context.Context, arg FindOneInsuranceClaimParams) (InsuranceandclaimsInsuranceClaim, error) {
	row := q.db.QueryRow(ctx, findOneInsuranceClaim, arg.InsuranceClaimID)
	var i InsuranceandclaimsInsuranceClaim
	err := row.Scan(
		&i.InsuranceClaimID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Deleted,
	)
	return i, err
}

const findOneInsuranceProvider = `-- name: FindOneInsuranceProvider :one
SELECT insurance_provider_id, created_at, updated_at, deleted_at, deleted FROM insuranceandclaims.insurance_providers
WHERE insurance_provider_id = $1
`

type FindOneInsuranceProviderParams struct {
	InsuranceProviderID pgtype.UUID `db:"insurance_provider_id" json:"insurance_provider_id"`
}

// FindOneInsuranceProvider
//
//	SELECT insurance_provider_id, created_at, updated_at, deleted_at, deleted FROM insuranceandclaims.insurance_providers
//	WHERE insurance_provider_id = $1
func (q *Queries) FindOneInsuranceProvider(ctx context.Context, arg FindOneInsuranceProviderParams) (InsuranceandclaimsInsuranceProvider, error) {
	row := q.db.QueryRow(ctx, findOneInsuranceProvider, arg.InsuranceProviderID)
	var i InsuranceandclaimsInsuranceProvider
	err := row.Scan(
		&i.InsuranceProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Deleted,
	)
	return i, err
}

const getInsuranceClaim = `-- name: GetInsuranceClaim :one
SELECT insurance_claim_id, created_at, updated_at, deleted_at, deleted FROM insuranceandclaims.insurance_claims
WHERE insurance_claim_id = $1
`

type GetInsuranceClaimParams struct {
	InsuranceClaimID pgtype.UUID `db:"insurance_claim_id" json:"insurance_claim_id"`
}

// GetInsuranceClaim
//
//	SELECT insurance_claim_id, created_at, updated_at, deleted_at, deleted FROM insuranceandclaims.insurance_claims
//	WHERE insurance_claim_id = $1
func (q *Queries) GetInsuranceClaim(ctx context.Context, arg GetInsuranceClaimParams) (InsuranceandclaimsInsuranceClaim, error) {
	row := q.db.QueryRow(ctx, getInsuranceClaim, arg.InsuranceClaimID)
	var i InsuranceandclaimsInsuranceClaim
	err := row.Scan(
		&i.InsuranceClaimID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Deleted,
	)
	return i, err
}

const getInsuranceProvider = `-- name: GetInsuranceProvider :one
SELECT insurance_provider_id, created_at, updated_at, deleted_at, deleted FROM insuranceandclaims.insurance_providers
WHERE insurance_provider_id = $1
`

type GetInsuranceProviderParams struct {
	InsuranceProviderID pgtype.UUID `db:"insurance_provider_id" json:"insurance_provider_id"`
}

// GetInsuranceProvider
//
//	SELECT insurance_provider_id, created_at, updated_at, deleted_at, deleted FROM insuranceandclaims.insurance_providers
//	WHERE insurance_provider_id = $1
func (q *Queries) GetInsuranceProvider(ctx context.Context, arg GetInsuranceProviderParams) (InsuranceandclaimsInsuranceProvider, error) {
	row := q.db.QueryRow(ctx, getInsuranceProvider, arg.InsuranceProviderID)
	var i InsuranceandclaimsInsuranceProvider
	err := row.Scan(
		&i.InsuranceProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Deleted,
	)
	return i, err
}

const updateInsuranceClaim = `-- name: UpdateInsuranceClaim :exec
UPDATE insuranceandclaims.insurance_claims
SET
    created_at = $2,
    updated_at = $3,
    deleted_at = $4,
    deleted = $5
    --,
    --claim_id
    --,
    --owner_id
    --,
    --pet_id
    --,
    --provider_id
    --,
    --invoice_id
    --,
    --policy_number
    --,
    --claim_amount
    --,
    --approved_amount
    --,
    --submission_date
    --,
    --resolution_date
    --,
    --status
    --,
    --notes
    --
    -- TODO
WHERE insurance_claim_id = $1
`

type UpdateInsuranceClaimParams struct {
	InsuranceClaimID pgtype.UUID        `db:"insurance_claim_id" json:"insurance_claim_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Deleted          bool               `db:"deleted" json:"deleted"`
}

// UpdateInsuranceClaim
//
//	UPDATE insuranceandclaims.insurance_claims
//	SET
//	    created_at = $2,
//	    updated_at = $3,
//	    deleted_at = $4,
//	    deleted = $5
//	    --,
//	    --claim_id
//	    --,
//	    --owner_id
//	    --,
//	    --pet_id
//	    --,
//	    --provider_id
//	    --,
//	    --invoice_id
//	    --,
//	    --policy_number
//	    --,
//	    --claim_amount
//	    --,
//	    --approved_amount
//	    --,
//	    --submission_date
//	    --,
//	    --resolution_date
//	    --,
//	    --status
//	    --,
//	    --notes
//	    --
//	    -- TODO
//	WHERE insurance_claim_id = $1
func (q *Queries) UpdateInsuranceClaim(ctx context.Context, arg UpdateInsuranceClaimParams) error {
	_, err := q.db.Exec(ctx, updateInsuranceClaim,
		arg.InsuranceClaimID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Deleted,
	)
	return err
}

const updateInsuranceProvider = `-- name: UpdateInsuranceProvider :exec
UPDATE insuranceandclaims.insurance_providers
SET
    created_at = $2,
    updated_at = $3,
    deleted_at = $4,
    deleted = $5
    --,
    --provider_id
    --,
    --name
    --,
    --contact_name
    --,
    --email
    --,
    --phone_number
    --,
    --claim_submission_url
    --,
    --status
    --
    -- TODO
WHERE insurance_provider_id = $1
`

type UpdateInsuranceProviderParams struct {
	InsuranceProviderID pgtype.UUID        `db:"insurance_provider_id" json:"insurance_provider_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Deleted             bool               `db:"deleted" json:"deleted"`
}

// UpdateInsuranceProvider
//
//	UPDATE insuranceandclaims.insurance_providers
//	SET
//	    created_at = $2,
//	    updated_at = $3,
//	    deleted_at = $4,
//	    deleted = $5
//	    --,
//	    --provider_id
//	    --,
//	    --name
//	    --,
//	    --contact_name
//	    --,
//	    --email
//	    --,
//	    --phone_number
//	    --,
//	    --claim_submission_url
//	    --,
//	    --status
//	    --
//	    -- TODO
//	WHERE insurance_provider_id = $1
func (q *Queries) UpdateInsuranceProvider(ctx context.Context, arg UpdateInsuranceProviderParams) error {
	_, err := q.db.Exec(ctx, updateInsuranceProvider,
		arg.InsuranceProviderID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Deleted,
	)
	return err
}
