/* tslint:disable */
/* eslint-disable */
/**
 * AppointmentScheduling API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Represents a scheduled appointment at the clinic
 * @export
 * @interface Appointment
 */
export interface Appointment {
  /**
   *
   * @type {string}
   * @memberof Appointment
   */
  appointmentId?: string;
  /**
   *
   * @type {string}
   * @memberof Appointment
   */
  petId?: string;
  /**
   *
   * @type {string}
   * @memberof Appointment
   */
  ownerId?: string;
  /**
   *
   * @type {string}
   * @memberof Appointment
   */
  veterinarianId?: string;
  /**
   *
   * @type {string}
   * @memberof Appointment
   */
  appointmentType?: string;
  /**
   *
   * @type {string}
   * @memberof Appointment
   */
  scheduledDate?: string;
  /**
   *
   * @type {string}
   * @memberof Appointment
   */
  scheduledTime?: string;
  /**
   *
   * @type {number}
   * @memberof Appointment
   */
  durationMinutes?: number;
  /**
   *
   * @type {string}
   * @memberof Appointment
   */
  status?: string;
  /**
   *
   * @type {string}
   * @memberof Appointment
   */
  notes?: string;
  /**
   *
   * @type {boolean}
   * @memberof Appointment
   */
  isTelemedicine?: boolean;
}

/**
 * Check if a given object implements the Appointment interface.
 */
export function instanceOfAppointment(value: object): value is Appointment {
  return true;
}

export function AppointmentFromJSON(json: any): Appointment {
  return AppointmentFromJSONTyped(json, false);
}

export function AppointmentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Appointment {
  if (json == null) {
    return json;
  }
  return {
    appointmentId:
      json["appointment_id"] == null ? undefined : json["appointment_id"],
    petId: json["pet_id"] == null ? undefined : json["pet_id"],
    ownerId: json["owner_id"] == null ? undefined : json["owner_id"],
    veterinarianId:
      json["veterinarian_id"] == null ? undefined : json["veterinarian_id"],
    appointmentType:
      json["appointment_type"] == null ? undefined : json["appointment_type"],
    scheduledDate:
      json["scheduled_date"] == null ? undefined : json["scheduled_date"],
    scheduledTime:
      json["scheduled_time"] == null ? undefined : json["scheduled_time"],
    durationMinutes:
      json["duration_minutes"] == null ? undefined : json["duration_minutes"],
    status: json["status"] == null ? undefined : json["status"],
    notes: json["notes"] == null ? undefined : json["notes"],
    isTelemedicine:
      json["is_telemedicine"] == null ? undefined : json["is_telemedicine"],
  };
}

export function AppointmentToJSON(json: any): Appointment {
  return AppointmentToJSONTyped(json, false);
}

export function AppointmentToJSONTyped(
  value?: Appointment | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    appointment_id: value["appointmentId"],
    pet_id: value["petId"],
    owner_id: value["ownerId"],
    veterinarian_id: value["veterinarianId"],
    appointment_type: value["appointmentType"],
    scheduled_date: value["scheduledDate"],
    scheduled_time: value["scheduledTime"],
    duration_minutes: value["durationMinutes"],
    status: value["status"],
    notes: value["notes"],
    is_telemedicine: value["isTelemedicine"],
  };
}
