# Environment variables are passed in via a .env file in the root of the project
name: go-full

include:
  # Application & Database
  - ./app/docker-compose.go-full.yml
  - ./database/docker-compose.postgres.yml
  
  # Mkdocs 
  - ./docs/docker-compose.docs.yml
  
  # Observability
  - ./observability/docker-compose.prometheus.yml
  - ./observability/docker-compose.jaeger.yml

  # Network Layer
  - ./network/docker-compose.nginx.yml