/* tslint:disable */
/* eslint-disable */
/**
 * PatientManagement API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RecordVaccination
 */
export interface RecordVaccination {
  /**
   *
   * @type {string}
   * @memberof RecordVaccination
   */
  petId?: string;
  /**
   *
   * @type {string}
   * @memberof RecordVaccination
   */
  vaccineName?: string;
  /**
   *
   * @type {string}
   * @memberof RecordVaccination
   */
  administeredDate?: string;
  /**
   *
   * @type {string}
   * @memberof RecordVaccination
   */
  expiryDate?: string;
  /**
   *
   * @type {string}
   * @memberof RecordVaccination
   */
  administeredBy?: string;
}

/**
 * Check if a given object implements the RecordVaccination interface.
 */
export function instanceOfRecordVaccination(
  value: object,
): value is RecordVaccination {
  return true;
}

export function RecordVaccinationFromJSON(json: any): RecordVaccination {
  return RecordVaccinationFromJSONTyped(json, false);
}

export function RecordVaccinationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecordVaccination {
  if (json == null) {
    return json;
  }
  return {
    petId: json["petId"] == null ? undefined : json["petId"],
    vaccineName: json["vaccineName"] == null ? undefined : json["vaccineName"],
    administeredDate:
      json["administeredDate"] == null ? undefined : json["administeredDate"],
    expiryDate: json["expiryDate"] == null ? undefined : json["expiryDate"],
    administeredBy:
      json["administeredBy"] == null ? undefined : json["administeredBy"],
  };
}

export function RecordVaccinationToJSON(json: any): RecordVaccination {
  return RecordVaccinationToJSONTyped(json, false);
}

export function RecordVaccinationToJSONTyped(
  value?: RecordVaccination | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    petId: value["petId"],
    vaccineName: value["vaccineName"],
    administeredDate: value["administeredDate"],
    expiryDate: value["expiryDate"],
    administeredBy: value["administeredBy"],
  };
}
