/* tslint:disable */
/* eslint-disable */
/**
 * PatientManagement API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdatePetDetails
 */
export interface UpdatePetDetails {
  /**
   *
   * @type {string}
   * @memberof UpdatePetDetails
   */
  petId?: string;
  /**
   *
   * @type {string}
   * @memberof UpdatePetDetails
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof UpdatePetDetails
   */
  weight?: number;
  /**
   *
   * @type {string}
   * @memberof UpdatePetDetails
   */
  microchipNumber?: string;
}

/**
 * Check if a given object implements the UpdatePetDetails interface.
 */
export function instanceOfUpdatePetDetails(
  value: object,
): value is UpdatePetDetails {
  return true;
}

export function UpdatePetDetailsFromJSON(json: any): UpdatePetDetails {
  return UpdatePetDetailsFromJSONTyped(json, false);
}

export function UpdatePetDetailsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdatePetDetails {
  if (json == null) {
    return json;
  }
  return {
    petId: json["petId"] == null ? undefined : json["petId"],
    name: json["name"] == null ? undefined : json["name"],
    weight: json["weight"] == null ? undefined : json["weight"],
    microchipNumber:
      json["microchipNumber"] == null ? undefined : json["microchipNumber"],
  };
}

export function UpdatePetDetailsToJSON(json: any): UpdatePetDetails {
  return UpdatePetDetailsToJSONTyped(json, false);
}

export function UpdatePetDetailsToJSONTyped(
  value?: UpdatePetDetails | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    petId: value["petId"],
    name: value["name"],
    weight: value["weight"],
    microchipNumber: value["microchipNumber"],
  };
}
