// Package inbound provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package inbound

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Error defines model for Error.
type Error struct {
	Code    *int32  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Exam defines model for Exam.
type Exam struct {
	ExamId              string     `json:"examId"`
	GradingCompleted    bool       `json:"gradingCompleted"`
	Questions           []Question `json:"questions"`
	TotalPointsEarned   *int32     `json:"totalPointsEarned,omitempty"`
	TotalPointsPossible int32      `json:"totalPointsPossible"`
}

// GradeQuestion defines model for GradeQuestion.
type GradeQuestion struct {
	Feedback string `json:"feedback"`
	Points   int32  `json:"points"`
}

// Question defines model for Question.
type Question struct {
	ExamId         string  `json:"examId"`
	Feedback       *string `json:"feedback,omitempty"`
	Graded         bool    `json:"graded"`
	PointsEarned   *int32  `json:"pointsEarned,omitempty"`
	PointsPossible *int32  `json:"pointsPossible,omitempty"`
	ProvidedAnswer *string `json:"providedAnswer,omitempty"`
	QuestionId     string  `json:"questionId"`
	QuestionIndex  int32   `json:"questionIndex"`
	QuestionType   string  `json:"questionType"`
}

// GradeExamQuestionJSONRequestBody defines body for GradeExamQuestion for application/json ContentType.
type GradeExamQuestionJSONRequestBody = GradeQuestion

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /v1/exams/ungraded)
	GetUngradedExams(w http.ResponseWriter, r *http.Request)

	// (GET /v1/exams/{examId})
	GetExam(w http.ResponseWriter, r *http.Request, examId string)

	// (GET /v1/exams/{examId}/questions/{questionIndex})
	GetExamQuestion(w http.ResponseWriter, r *http.Request, examId string, questionIndex int32)

	// (PATCH /v1/exams/{examId}/questions/{questionIndex}/grade)
	GradeExamQuestion(w http.ResponseWriter, r *http.Request, examId string, questionIndex int32)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /v1/exams/ungraded)
func (_ Unimplemented) GetUngradedExams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/exams/{examId})
func (_ Unimplemented) GetExam(w http.ResponseWriter, r *http.Request, examId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/exams/{examId}/questions/{questionIndex})
func (_ Unimplemented) GetExamQuestion(w http.ResponseWriter, r *http.Request, examId string, questionIndex int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /v1/exams/{examId}/questions/{questionIndex}/grade)
func (_ Unimplemented) GradeExamQuestion(w http.ResponseWriter, r *http.Request, examId string, questionIndex int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetUngradedExams operation middleware
func (siw *ServerInterfaceWrapper) GetUngradedExams(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUngradedExams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExam operation middleware
func (siw *ServerInterfaceWrapper) GetExam(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "examId" -------------
	var examId string

	err = runtime.BindStyledParameterWithOptions("simple", "examId", chi.URLParam(r, "examId"), &examId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "examId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExam(w, r, examId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExamQuestion operation middleware
func (siw *ServerInterfaceWrapper) GetExamQuestion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "examId" -------------
	var examId string

	err = runtime.BindStyledParameterWithOptions("simple", "examId", chi.URLParam(r, "examId"), &examId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "examId", Err: err})
		return
	}

	// ------------- Path parameter "questionIndex" -------------
	var questionIndex int32

	err = runtime.BindStyledParameterWithOptions("simple", "questionIndex", chi.URLParam(r, "questionIndex"), &questionIndex, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questionIndex", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExamQuestion(w, r, examId, questionIndex)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GradeExamQuestion operation middleware
func (siw *ServerInterfaceWrapper) GradeExamQuestion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "examId" -------------
	var examId string

	err = runtime.BindStyledParameterWithOptions("simple", "examId", chi.URLParam(r, "examId"), &examId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "examId", Err: err})
		return
	}

	// ------------- Path parameter "questionIndex" -------------
	var questionIndex int32

	err = runtime.BindStyledParameterWithOptions("simple", "questionIndex", chi.URLParam(r, "questionIndex"), &questionIndex, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questionIndex", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GradeExamQuestion(w, r, examId, questionIndex)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/exams/ungraded", wrapper.GetUngradedExams)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/exams/{examId}", wrapper.GetExam)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/exams/{examId}/questions/{questionIndex}", wrapper.GetExamQuestion)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/exams/{examId}/questions/{questionIndex}/grade", wrapper.GradeExamQuestion)
	})

	return r
}

type GetUngradedExamsRequestObject struct {
}

type GetUngradedExamsResponseObject interface {
	VisitGetUngradedExamsResponse(w http.ResponseWriter) error
}

type GetUngradedExams200JSONResponse []Exam

func (response GetUngradedExams200JSONResponse) VisitGetUngradedExamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUngradedExamsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetUngradedExamsdefaultJSONResponse) VisitGetUngradedExamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetExamRequestObject struct {
	ExamId string `json:"examId"`
}

type GetExamResponseObject interface {
	VisitGetExamResponse(w http.ResponseWriter) error
}

type GetExam200JSONResponse Exam

func (response GetExam200JSONResponse) VisitGetExamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetExamdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetExamdefaultJSONResponse) VisitGetExamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetExamQuestionRequestObject struct {
	ExamId        string `json:"examId"`
	QuestionIndex int32  `json:"questionIndex"`
}

type GetExamQuestionResponseObject interface {
	VisitGetExamQuestionResponse(w http.ResponseWriter) error
}

type GetExamQuestion200JSONResponse Question

func (response GetExamQuestion200JSONResponse) VisitGetExamQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetExamQuestiondefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetExamQuestiondefaultJSONResponse) VisitGetExamQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GradeExamQuestionRequestObject struct {
	ExamId        string `json:"examId"`
	QuestionIndex int32  `json:"questionIndex"`
	Body          *GradeExamQuestionJSONRequestBody
}

type GradeExamQuestionResponseObject interface {
	VisitGradeExamQuestionResponse(w http.ResponseWriter) error
}

type GradeExamQuestion201JSONResponse Exam

func (response GradeExamQuestion201JSONResponse) VisitGradeExamQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type GradeExamQuestiondefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GradeExamQuestiondefaultJSONResponse) VisitGradeExamQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /v1/exams/ungraded)
	GetUngradedExams(ctx context.Context, request GetUngradedExamsRequestObject) (GetUngradedExamsResponseObject, error)

	// (GET /v1/exams/{examId})
	GetExam(ctx context.Context, request GetExamRequestObject) (GetExamResponseObject, error)

	// (GET /v1/exams/{examId}/questions/{questionIndex})
	GetExamQuestion(ctx context.Context, request GetExamQuestionRequestObject) (GetExamQuestionResponseObject, error)

	// (PATCH /v1/exams/{examId}/questions/{questionIndex}/grade)
	GradeExamQuestion(ctx context.Context, request GradeExamQuestionRequestObject) (GradeExamQuestionResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetUngradedExams operation middleware
func (sh *strictHandler) GetUngradedExams(w http.ResponseWriter, r *http.Request) {
	var request GetUngradedExamsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUngradedExams(ctx, request.(GetUngradedExamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUngradedExams")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUngradedExamsResponseObject); ok {
		if err := validResponse.VisitGetUngradedExamsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetExam operation middleware
func (sh *strictHandler) GetExam(w http.ResponseWriter, r *http.Request, examId string) {
	var request GetExamRequestObject

	request.ExamId = examId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetExam(ctx, request.(GetExamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExam")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetExamResponseObject); ok {
		if err := validResponse.VisitGetExamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetExamQuestion operation middleware
func (sh *strictHandler) GetExamQuestion(w http.ResponseWriter, r *http.Request, examId string, questionIndex int32) {
	var request GetExamQuestionRequestObject

	request.ExamId = examId
	request.QuestionIndex = questionIndex

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetExamQuestion(ctx, request.(GetExamQuestionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExamQuestion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetExamQuestionResponseObject); ok {
		if err := validResponse.VisitGetExamQuestionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GradeExamQuestion operation middleware
func (sh *strictHandler) GradeExamQuestion(w http.ResponseWriter, r *http.Request, examId string, questionIndex int32) {
	var request GradeExamQuestionRequestObject

	request.ExamId = examId
	request.QuestionIndex = questionIndex

	var body GradeExamQuestionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GradeExamQuestion(ctx, request.(GradeExamQuestionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GradeExamQuestion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GradeExamQuestionResponseObject); ok {
		if err := validResponse.VisitGradeExamQuestionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xWTW/bOBD9K8bsHonISW6+ZRdBkFsKtKcgB1oay0wlkhmOXAeG/nsxlPXhWHactina",
	"nEyLw5k37z0NtYHUld5ZtBxgtoGQLrHUcXlN5EgWnpxHYoPxceoylN+Fo1IzzMBYvrwABfzssfmLORLU",
	"CkoMQecxersZmIzNoa67cDd/xJQl+nqty/1yuNblbTaSQkFOOjM2/9+VvkDGYdDcuQK1lainCgMbZ2M2",
	"w1jGxb+EC5jBP0nffrLtPfm0PQE9Sk2kn+N/x7q4c8ZyuNZkm6InUDE4d+dCMPPiNBJrBYRPlSGpdN+y",
	"MdL7eIlh+w8jnN+QzrDrd4/8BWI21+nXUfp9LPUjXWxPqj7/GLbDsI544ihiIe2QTfzbNfVvl1NJJyuT",
	"YXZlwzekUZitZAda7LZthusTq7ZnPsedsddxqM8AgOott1v3Rc6O3H0lJbuxCxfrGhamou+MzSdXd7eg",
	"YIUUotBwfjY9mwpg59Fqb2AGl/GRAq95GdVPVueJgApJZXtFc2T5EZvoljy4Qf6yjZHpIpYjDN7Z0Bjp",
	"YjptRppltPG89r4wacyQPIbGfM1cOHl8xDm2NzqEhQxDSsY3poYW2SQ2MyFkMrjCbBKqNMUQFlVRxJmT",
	"4UJXBb8J6VGAcbCPIKosrj2mLJjamFoNCN80ZqiPER7bF7lIl8hIAWb3GzCSXyQEBVaXQkxnrN56TBWq",
	"QRcvbfrwk/q9Lts+KfJ8kiFrU/xdIiXd6E82O+/uq/J1k/edZFSjiV7Ol8P5Xr9v3tMo/efBAbO0jXwQ",
	"tyRxTMVbWHO6HHGN7H8g38SE/7ns+ZfJs/uZVe/et4Ky3vPr+e8ZbJ1Xt3fRn2XUWkFAWrUuqqiAGSyZ",
	"fZglyWbpAosH6kS+FBSsNBk9LxoG201Zd01A4VJdyJakf6i/BwAA//8/mYFB/gwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
