// Package api_client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api_client

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	Code    *int32  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// InventoryItem Represents the stock level of a product in the clinic
type InventoryItem struct {
	InventoryItemId   *string `json:"inventory_item_id,omitempty"`
	LastRestockedDate *string `json:"last_restocked_date,omitempty"`
	ProductId         *string `json:"product_id,omitempty"`
	QuantityOnHand    *int32  `json:"quantity_on_hand,omitempty"`
	ReorderQuantity   *int32  `json:"reorder_quantity,omitempty"`
	ReorderThreshold  *int32  `json:"reorder_threshold,omitempty"`
}

// Product Represents a product available for sale or use in the clinic
type Product struct {
	Category    *string  `json:"category,omitempty"`
	Description *string  `json:"description,omitempty"`
	IsActive    *bool    `json:"is_active,omitempty"`
	Name        *string  `json:"name,omitempty"`
	ProductId   *string  `json:"product_id,omitempty"`
	Sku         *string  `json:"sku,omitempty"`
	SupplierId  *string  `json:"supplier_id,omitempty"`
	UnitPrice   *float32 `json:"unit_price,omitempty"`
}

// PurchaseOrder Represents a purchase order placed with a supplier for stock replenishment
type PurchaseOrder struct {
	ExpectedDeliveryDate *string  `json:"expected_delivery_date,omitempty"`
	LineItems            *string  `json:"line_items,omitempty"`
	OrderDate            *string  `json:"order_date,omitempty"`
	PurchaseOrderId      *string  `json:"purchase_order_id,omitempty"`
	Status               *string  `json:"status,omitempty"`
	SupplierId           *string  `json:"supplier_id,omitempty"`
	TotalCost            *float32 `json:"total_cost,omitempty"`
}

// Supplier Represents a supplier providing products or medical supplies to the clinic
type Supplier struct {
	ContactName       *string `json:"contact_name,omitempty"`
	Email             *string `json:"email,omitempty"`
	Name              *string `json:"name,omitempty"`
	PhoneNumber       *string `json:"phone_number,omitempty"`
	ProductCategories *string `json:"product_categories,omitempty"`
	Status            *string `json:"status,omitempty"`
	SupplierId        *string `json:"supplier_id,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// FindAllInventoryItems request
	FindAllInventoryItems(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindOneInventoryItem request
	FindOneInventoryItem(ctx context.Context, inventoryItemId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindAllProducts request
	FindAllProducts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindOneProduct request
	FindOneProduct(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindAllPurchaseOrders request
	FindAllPurchaseOrders(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindOnePurchaseOrder request
	FindOnePurchaseOrder(ctx context.Context, purchaseOrderId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindAllSuppliers request
	FindAllSuppliers(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindOneSupplier request
	FindOneSupplier(ctx context.Context, supplierId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) FindAllInventoryItems(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindAllInventoryItemsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindOneInventoryItem(ctx context.Context, inventoryItemId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindOneInventoryItemRequest(c.Server, inventoryItemId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindAllProducts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindAllProductsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindOneProduct(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindOneProductRequest(c.Server, productId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindAllPurchaseOrders(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindAllPurchaseOrdersRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindOnePurchaseOrder(ctx context.Context, purchaseOrderId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindOnePurchaseOrderRequest(c.Server, purchaseOrderId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindAllSuppliers(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindAllSuppliersRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindOneSupplier(ctx context.Context, supplierId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindOneSupplierRequest(c.Server, supplierId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewFindAllInventoryItemsRequest generates requests for FindAllInventoryItems
func NewFindAllInventoryItemsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/inventoryitems")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindOneInventoryItemRequest generates requests for FindOneInventoryItem
func NewFindOneInventoryItemRequest(server string, inventoryItemId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "inventoryItemId", runtime.ParamLocationPath, inventoryItemId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/inventoryitems/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindAllProductsRequest generates requests for FindAllProducts
func NewFindAllProductsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/products")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindOneProductRequest generates requests for FindOneProduct
func NewFindOneProductRequest(server string, productId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "productId", runtime.ParamLocationPath, productId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/products/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindAllPurchaseOrdersRequest generates requests for FindAllPurchaseOrders
func NewFindAllPurchaseOrdersRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/purchaseorders")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindOnePurchaseOrderRequest generates requests for FindOnePurchaseOrder
func NewFindOnePurchaseOrderRequest(server string, purchaseOrderId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "purchaseOrderId", runtime.ParamLocationPath, purchaseOrderId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/purchaseorders/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindAllSuppliersRequest generates requests for FindAllSuppliers
func NewFindAllSuppliersRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/suppliers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindOneSupplierRequest generates requests for FindOneSupplier
func NewFindOneSupplierRequest(server string, supplierId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "supplierId", runtime.ParamLocationPath, supplierId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/suppliers/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// FindAllInventoryItemsWithResponse request
	FindAllInventoryItemsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllInventoryItemsResponse, error)

	// FindOneInventoryItemWithResponse request
	FindOneInventoryItemWithResponse(ctx context.Context, inventoryItemId string, reqEditors ...RequestEditorFn) (*FindOneInventoryItemResponse, error)

	// FindAllProductsWithResponse request
	FindAllProductsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllProductsResponse, error)

	// FindOneProductWithResponse request
	FindOneProductWithResponse(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*FindOneProductResponse, error)

	// FindAllPurchaseOrdersWithResponse request
	FindAllPurchaseOrdersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllPurchaseOrdersResponse, error)

	// FindOnePurchaseOrderWithResponse request
	FindOnePurchaseOrderWithResponse(ctx context.Context, purchaseOrderId string, reqEditors ...RequestEditorFn) (*FindOnePurchaseOrderResponse, error)

	// FindAllSuppliersWithResponse request
	FindAllSuppliersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllSuppliersResponse, error)

	// FindOneSupplierWithResponse request
	FindOneSupplierWithResponse(ctx context.Context, supplierId string, reqEditors ...RequestEditorFn) (*FindOneSupplierResponse, error)
}

type FindAllInventoryItemsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]InventoryItem
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindAllInventoryItemsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindAllInventoryItemsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindOneInventoryItemResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *InventoryItem
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindOneInventoryItemResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindOneInventoryItemResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindAllProductsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Product
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindAllProductsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindAllProductsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindOneProductResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Product
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindOneProductResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindOneProductResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindAllPurchaseOrdersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]PurchaseOrder
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindAllPurchaseOrdersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindAllPurchaseOrdersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindOnePurchaseOrderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PurchaseOrder
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindOnePurchaseOrderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindOnePurchaseOrderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindAllSuppliersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Supplier
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindAllSuppliersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindAllSuppliersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindOneSupplierResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Supplier
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindOneSupplierResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindOneSupplierResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// FindAllInventoryItemsWithResponse request returning *FindAllInventoryItemsResponse
func (c *ClientWithResponses) FindAllInventoryItemsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllInventoryItemsResponse, error) {
	rsp, err := c.FindAllInventoryItems(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindAllInventoryItemsResponse(rsp)
}

// FindOneInventoryItemWithResponse request returning *FindOneInventoryItemResponse
func (c *ClientWithResponses) FindOneInventoryItemWithResponse(ctx context.Context, inventoryItemId string, reqEditors ...RequestEditorFn) (*FindOneInventoryItemResponse, error) {
	rsp, err := c.FindOneInventoryItem(ctx, inventoryItemId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindOneInventoryItemResponse(rsp)
}

// FindAllProductsWithResponse request returning *FindAllProductsResponse
func (c *ClientWithResponses) FindAllProductsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllProductsResponse, error) {
	rsp, err := c.FindAllProducts(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindAllProductsResponse(rsp)
}

// FindOneProductWithResponse request returning *FindOneProductResponse
func (c *ClientWithResponses) FindOneProductWithResponse(ctx context.Context, productId string, reqEditors ...RequestEditorFn) (*FindOneProductResponse, error) {
	rsp, err := c.FindOneProduct(ctx, productId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindOneProductResponse(rsp)
}

// FindAllPurchaseOrdersWithResponse request returning *FindAllPurchaseOrdersResponse
func (c *ClientWithResponses) FindAllPurchaseOrdersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllPurchaseOrdersResponse, error) {
	rsp, err := c.FindAllPurchaseOrders(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindAllPurchaseOrdersResponse(rsp)
}

// FindOnePurchaseOrderWithResponse request returning *FindOnePurchaseOrderResponse
func (c *ClientWithResponses) FindOnePurchaseOrderWithResponse(ctx context.Context, purchaseOrderId string, reqEditors ...RequestEditorFn) (*FindOnePurchaseOrderResponse, error) {
	rsp, err := c.FindOnePurchaseOrder(ctx, purchaseOrderId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindOnePurchaseOrderResponse(rsp)
}

// FindAllSuppliersWithResponse request returning *FindAllSuppliersResponse
func (c *ClientWithResponses) FindAllSuppliersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllSuppliersResponse, error) {
	rsp, err := c.FindAllSuppliers(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindAllSuppliersResponse(rsp)
}

// FindOneSupplierWithResponse request returning *FindOneSupplierResponse
func (c *ClientWithResponses) FindOneSupplierWithResponse(ctx context.Context, supplierId string, reqEditors ...RequestEditorFn) (*FindOneSupplierResponse, error) {
	rsp, err := c.FindOneSupplier(ctx, supplierId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindOneSupplierResponse(rsp)
}

// ParseFindAllInventoryItemsResponse parses an HTTP response from a FindAllInventoryItemsWithResponse call
func ParseFindAllInventoryItemsResponse(rsp *http.Response) (*FindAllInventoryItemsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindAllInventoryItemsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []InventoryItem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindOneInventoryItemResponse parses an HTTP response from a FindOneInventoryItemWithResponse call
func ParseFindOneInventoryItemResponse(rsp *http.Response) (*FindOneInventoryItemResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindOneInventoryItemResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InventoryItem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindAllProductsResponse parses an HTTP response from a FindAllProductsWithResponse call
func ParseFindAllProductsResponse(rsp *http.Response) (*FindAllProductsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindAllProductsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Product
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindOneProductResponse parses an HTTP response from a FindOneProductWithResponse call
func ParseFindOneProductResponse(rsp *http.Response) (*FindOneProductResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindOneProductResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Product
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindAllPurchaseOrdersResponse parses an HTTP response from a FindAllPurchaseOrdersWithResponse call
func ParseFindAllPurchaseOrdersResponse(rsp *http.Response) (*FindAllPurchaseOrdersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindAllPurchaseOrdersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []PurchaseOrder
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindOnePurchaseOrderResponse parses an HTTP response from a FindOnePurchaseOrderWithResponse call
func ParseFindOnePurchaseOrderResponse(rsp *http.Response) (*FindOnePurchaseOrderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindOnePurchaseOrderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PurchaseOrder
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindAllSuppliersResponse parses an HTTP response from a FindAllSuppliersWithResponse call
func ParseFindAllSuppliersResponse(rsp *http.Response) (*FindAllSuppliersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindAllSuppliersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Supplier
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindOneSupplierResponse parses an HTTP response from a FindOneSupplierWithResponse call
func ParseFindOneSupplierResponse(rsp *http.Response) (*FindOneSupplierResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindOneSupplierResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Supplier
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
