/* tslint:disable */
/* eslint-disable */
/**
 * InsuranceAndClaims API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Represents a pet insurance company partnered with the clinic
 * @export
 * @interface InsuranceProvider
 */
export interface InsuranceProvider {
  /**
   *
   * @type {string}
   * @memberof InsuranceProvider
   */
  providerId?: string;
  /**
   *
   * @type {string}
   * @memberof InsuranceProvider
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof InsuranceProvider
   */
  contactName?: string;
  /**
   *
   * @type {string}
   * @memberof InsuranceProvider
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof InsuranceProvider
   */
  phoneNumber?: string;
  /**
   *
   * @type {string}
   * @memberof InsuranceProvider
   */
  claimSubmissionUrl?: string;
  /**
   *
   * @type {string}
   * @memberof InsuranceProvider
   */
  status?: string;
}

/**
 * Check if a given object implements the InsuranceProvider interface.
 */
export function instanceOfInsuranceProvider(
  value: object,
): value is InsuranceProvider {
  return true;
}

export function InsuranceProviderFromJSON(json: any): InsuranceProvider {
  return InsuranceProviderFromJSONTyped(json, false);
}

export function InsuranceProviderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InsuranceProvider {
  if (json == null) {
    return json;
  }
  return {
    providerId: json["provider_id"] == null ? undefined : json["provider_id"],
    name: json["name"] == null ? undefined : json["name"],
    contactName:
      json["contact_name"] == null ? undefined : json["contact_name"],
    email: json["email"] == null ? undefined : json["email"],
    phoneNumber:
      json["phone_number"] == null ? undefined : json["phone_number"],
    claimSubmissionUrl:
      json["claim_submission_url"] == null
        ? undefined
        : json["claim_submission_url"],
    status: json["status"] == null ? undefined : json["status"],
  };
}

export function InsuranceProviderToJSON(json: any): InsuranceProvider {
  return InsuranceProviderToJSONTyped(json, false);
}

export function InsuranceProviderToJSONTyped(
  value?: InsuranceProvider | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    provider_id: value["providerId"],
    name: value["name"],
    contact_name: value["contactName"],
    email: value["email"],
    phone_number: value["phoneNumber"],
    claim_submission_url: value["claimSubmissionUrl"],
    status: value["status"],
  };
}
