/* tslint:disable */
/* eslint-disable */
/**
 * InsuranceAndClaims API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RegisterInsuranceProvider
 */
export interface RegisterInsuranceProvider {
  /**
   *
   * @type {string}
   * @memberof RegisterInsuranceProvider
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof RegisterInsuranceProvider
   */
  contactName?: string;
  /**
   *
   * @type {string}
   * @memberof RegisterInsuranceProvider
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof RegisterInsuranceProvider
   */
  phoneNumber?: string;
  /**
   *
   * @type {string}
   * @memberof RegisterInsuranceProvider
   */
  claimSubmissionUrl?: string;
}

/**
 * Check if a given object implements the RegisterInsuranceProvider interface.
 */
export function instanceOfRegisterInsuranceProvider(
  value: object,
): value is RegisterInsuranceProvider {
  return true;
}

export function RegisterInsuranceProviderFromJSON(
  json: any,
): RegisterInsuranceProvider {
  return RegisterInsuranceProviderFromJSONTyped(json, false);
}

export function RegisterInsuranceProviderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RegisterInsuranceProvider {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    contactName: json["contactName"] == null ? undefined : json["contactName"],
    email: json["email"] == null ? undefined : json["email"],
    phoneNumber: json["phoneNumber"] == null ? undefined : json["phoneNumber"],
    claimSubmissionUrl:
      json["claimSubmissionUrl"] == null
        ? undefined
        : json["claimSubmissionUrl"],
  };
}

export function RegisterInsuranceProviderToJSON(
  json: any,
): RegisterInsuranceProvider {
  return RegisterInsuranceProviderToJSONTyped(json, false);
}

export function RegisterInsuranceProviderToJSONTyped(
  value?: RegisterInsuranceProvider | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    contactName: value["contactName"],
    email: value["email"],
    phoneNumber: value["phoneNumber"],
    claimSubmissionUrl: value["claimSubmissionUrl"],
  };
}
