// Package api_client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api_client

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	Code    *int32  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Notification Represents a notification sent to a pet owner or staff member
type Notification struct {
	Channel          *string `json:"channel,omitempty"`
	MessageBody      *string `json:"message_body,omitempty"`
	NotificationId   *string `json:"notification_id,omitempty"`
	NotificationType *string `json:"notification_type,omitempty"`
	RecipientId      *string `json:"recipient_id,omitempty"`
	RecipientType    *string `json:"recipient_type,omitempty"`
	SentAt           *string `json:"sent_at,omitempty"`
	Status           *string `json:"status,omitempty"`
	Subject          *string `json:"subject,omitempty"`
}

// NotificationTemplate Represents a reusable template for generating notifications
type NotificationTemplate struct {
	BodyTemplate     *string `json:"body_template,omitempty"`
	Channel          *string `json:"channel,omitempty"`
	IsActive         *bool   `json:"is_active,omitempty"`
	Name             *string `json:"name,omitempty"`
	NotificationType *string `json:"notification_type,omitempty"`
	SubjectTemplate  *string `json:"subject_template,omitempty"`
	TemplateId       *string `json:"template_id,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// FindAllNotifications request
	FindAllNotifications(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindOneNotification request
	FindOneNotification(ctx context.Context, notificationId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindAllNotificationTemplates request
	FindAllNotificationTemplates(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FindOneNotificationTemplate request
	FindOneNotificationTemplate(ctx context.Context, notificationTemplateId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) FindAllNotifications(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindAllNotificationsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindOneNotification(ctx context.Context, notificationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindOneNotificationRequest(c.Server, notificationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindAllNotificationTemplates(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindAllNotificationTemplatesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FindOneNotificationTemplate(ctx context.Context, notificationTemplateId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFindOneNotificationTemplateRequest(c.Server, notificationTemplateId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewFindAllNotificationsRequest generates requests for FindAllNotifications
func NewFindAllNotificationsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/notifications")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindOneNotificationRequest generates requests for FindOneNotification
func NewFindOneNotificationRequest(server string, notificationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "notificationId", runtime.ParamLocationPath, notificationId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/notifications/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindAllNotificationTemplatesRequest generates requests for FindAllNotificationTemplates
func NewFindAllNotificationTemplatesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/notificationtemplates")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFindOneNotificationTemplateRequest generates requests for FindOneNotificationTemplate
func NewFindOneNotificationTemplateRequest(server string, notificationTemplateId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "notificationTemplateId", runtime.ParamLocationPath, notificationTemplateId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/notificationtemplates/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// FindAllNotificationsWithResponse request
	FindAllNotificationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllNotificationsResponse, error)

	// FindOneNotificationWithResponse request
	FindOneNotificationWithResponse(ctx context.Context, notificationId string, reqEditors ...RequestEditorFn) (*FindOneNotificationResponse, error)

	// FindAllNotificationTemplatesWithResponse request
	FindAllNotificationTemplatesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllNotificationTemplatesResponse, error)

	// FindOneNotificationTemplateWithResponse request
	FindOneNotificationTemplateWithResponse(ctx context.Context, notificationTemplateId string, reqEditors ...RequestEditorFn) (*FindOneNotificationTemplateResponse, error)
}

type FindAllNotificationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Notification
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindAllNotificationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindAllNotificationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindOneNotificationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Notification
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindOneNotificationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindOneNotificationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindAllNotificationTemplatesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]NotificationTemplate
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindAllNotificationTemplatesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindAllNotificationTemplatesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FindOneNotificationTemplateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NotificationTemplate
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r FindOneNotificationTemplateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FindOneNotificationTemplateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// FindAllNotificationsWithResponse request returning *FindAllNotificationsResponse
func (c *ClientWithResponses) FindAllNotificationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllNotificationsResponse, error) {
	rsp, err := c.FindAllNotifications(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindAllNotificationsResponse(rsp)
}

// FindOneNotificationWithResponse request returning *FindOneNotificationResponse
func (c *ClientWithResponses) FindOneNotificationWithResponse(ctx context.Context, notificationId string, reqEditors ...RequestEditorFn) (*FindOneNotificationResponse, error) {
	rsp, err := c.FindOneNotification(ctx, notificationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindOneNotificationResponse(rsp)
}

// FindAllNotificationTemplatesWithResponse request returning *FindAllNotificationTemplatesResponse
func (c *ClientWithResponses) FindAllNotificationTemplatesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FindAllNotificationTemplatesResponse, error) {
	rsp, err := c.FindAllNotificationTemplates(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindAllNotificationTemplatesResponse(rsp)
}

// FindOneNotificationTemplateWithResponse request returning *FindOneNotificationTemplateResponse
func (c *ClientWithResponses) FindOneNotificationTemplateWithResponse(ctx context.Context, notificationTemplateId string, reqEditors ...RequestEditorFn) (*FindOneNotificationTemplateResponse, error) {
	rsp, err := c.FindOneNotificationTemplate(ctx, notificationTemplateId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFindOneNotificationTemplateResponse(rsp)
}

// ParseFindAllNotificationsResponse parses an HTTP response from a FindAllNotificationsWithResponse call
func ParseFindAllNotificationsResponse(rsp *http.Response) (*FindAllNotificationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindAllNotificationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Notification
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindOneNotificationResponse parses an HTTP response from a FindOneNotificationWithResponse call
func ParseFindOneNotificationResponse(rsp *http.Response) (*FindOneNotificationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindOneNotificationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Notification
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindAllNotificationTemplatesResponse parses an HTTP response from a FindAllNotificationTemplatesWithResponse call
func ParseFindAllNotificationTemplatesResponse(rsp *http.Response) (*FindAllNotificationTemplatesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindAllNotificationTemplatesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []NotificationTemplate
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFindOneNotificationTemplateResponse parses an HTTP response from a FindOneNotificationTemplateWithResponse call
func ParseFindOneNotificationTemplateResponse(rsp *http.Response) (*FindOneNotificationTemplateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FindOneNotificationTemplateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NotificationTemplate
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
