/* tslint:disable */
/* eslint-disable */
/**
 * OwnerManagement API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateOwnerProfile
 */
export interface UpdateOwnerProfile {
  /**
   *
   * @type {string}
   * @memberof UpdateOwnerProfile
   */
  ownerId?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateOwnerProfile
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateOwnerProfile
   */
  phoneNumber?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateOwnerProfile
   */
  address?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateOwnerProfile
   */
  communicationPreference?: string;
}

/**
 * Check if a given object implements the UpdateOwnerProfile interface.
 */
export function instanceOfUpdateOwnerProfile(
  value: object,
): value is UpdateOwnerProfile {
  return true;
}

export function UpdateOwnerProfileFromJSON(json: any): UpdateOwnerProfile {
  return UpdateOwnerProfileFromJSONTyped(json, false);
}

export function UpdateOwnerProfileFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateOwnerProfile {
  if (json == null) {
    return json;
  }
  return {
    ownerId: json["ownerId"] == null ? undefined : json["ownerId"],
    email: json["email"] == null ? undefined : json["email"],
    phoneNumber: json["phoneNumber"] == null ? undefined : json["phoneNumber"],
    address: json["address"] == null ? undefined : json["address"],
    communicationPreference:
      json["communicationPreference"] == null
        ? undefined
        : json["communicationPreference"],
  };
}

export function UpdateOwnerProfileToJSON(json: any): UpdateOwnerProfile {
  return UpdateOwnerProfileToJSONTyped(json, false);
}

export function UpdateOwnerProfileToJSONTyped(
  value?: UpdateOwnerProfile | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ownerId: value["ownerId"],
    email: value["email"],
    phoneNumber: value["phoneNumber"],
    address: value["address"],
    communicationPreference: value["communicationPreference"],
  };
}
