/* tslint:disable */
/* eslint-disable */
/**
 * InventoryAndProducts API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AddProductToCatalog
 */
export interface AddProductToCatalog {
  /**
   *
   * @type {string}
   * @memberof AddProductToCatalog
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof AddProductToCatalog
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof AddProductToCatalog
   */
  category?: string;
  /**
   *
   * @type {number}
   * @memberof AddProductToCatalog
   */
  unitPrice?: number;
  /**
   *
   * @type {string}
   * @memberof AddProductToCatalog
   */
  sku?: string;
  /**
   *
   * @type {string}
   * @memberof AddProductToCatalog
   */
  supplierId?: string;
}

/**
 * Check if a given object implements the AddProductToCatalog interface.
 */
export function instanceOfAddProductToCatalog(
  value: object,
): value is AddProductToCatalog {
  return true;
}

export function AddProductToCatalogFromJSON(json: any): AddProductToCatalog {
  return AddProductToCatalogFromJSONTyped(json, false);
}

export function AddProductToCatalogFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddProductToCatalog {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    description: json["description"] == null ? undefined : json["description"],
    category: json["category"] == null ? undefined : json["category"],
    unitPrice: json["unitPrice"] == null ? undefined : json["unitPrice"],
    sku: json["sku"] == null ? undefined : json["sku"],
    supplierId: json["supplierId"] == null ? undefined : json["supplierId"],
  };
}

export function AddProductToCatalogToJSON(json: any): AddProductToCatalog {
  return AddProductToCatalogToJSONTyped(json, false);
}

export function AddProductToCatalogToJSONTyped(
  value?: AddProductToCatalog | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    description: value["description"],
    category: value["category"],
    unitPrice: value["unitPrice"],
    sku: value["sku"],
    supplierId: value["supplierId"],
  };
}
