/* tslint:disable */
/* eslint-disable */
/**
 * InventoryAndProducts API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ReceivePurchaseOrder
 */
export interface ReceivePurchaseOrder {
  /**
   *
   * @type {string}
   * @memberof ReceivePurchaseOrder
   */
  purchaseOrderId?: string;
  /**
   *
   * @type {string}
   * @memberof ReceivePurchaseOrder
   */
  receivedDate?: string;
}

/**
 * Check if a given object implements the ReceivePurchaseOrder interface.
 */
export function instanceOfReceivePurchaseOrder(
  value: object,
): value is ReceivePurchaseOrder {
  return true;
}

export function ReceivePurchaseOrderFromJSON(json: any): ReceivePurchaseOrder {
  return ReceivePurchaseOrderFromJSONTyped(json, false);
}

export function ReceivePurchaseOrderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReceivePurchaseOrder {
  if (json == null) {
    return json;
  }
  return {
    purchaseOrderId:
      json["purchaseOrderId"] == null ? undefined : json["purchaseOrderId"],
    receivedDate:
      json["receivedDate"] == null ? undefined : json["receivedDate"],
  };
}

export function ReceivePurchaseOrderToJSON(json: any): ReceivePurchaseOrder {
  return ReceivePurchaseOrderToJSONTyped(json, false);
}

export function ReceivePurchaseOrderToJSONTyped(
  value?: ReceivePurchaseOrder | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    purchaseOrderId: value["purchaseOrderId"],
    receivedDate: value["receivedDate"],
  };
}
