// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package outbound

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationsandcommunicationsNotification struct {
	NotificationID pgtype.UUID        `db:"notification_id" json:"notification_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Deleted        bool               `db:"deleted" json:"deleted"`
}

type NotificationsandcommunicationsNotificationTemplate struct {
	NotificationTemplateID pgtype.UUID        `db:"notification_template_id" json:"notification_template_id"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Deleted                bool               `db:"deleted" json:"deleted"`
}
