/* tslint:disable */
/* eslint-disable */
/**
 * PingPong
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * A PingPong data trend
 * @export
 * @interface Trend
 */
export interface Trend {
  /**
   * The keys of the defined trend dimension
   * @type {Array<string>}
   * @memberof Trend
   */
  dimensionKeys?: Array<string>;
  /**
   * values associated with the trend
   * @type {Array<number>}
   * @memberof Trend
   */
  dimensionValues?: Array<number>;
}

/**
 * Check if a given object implements the Trend interface.
 */
export function instanceOfTrend(value: object): value is Trend {
  return true;
}

export function TrendFromJSON(json: any): Trend {
  return TrendFromJSONTyped(json, false);
}

export function TrendFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Trend {
  if (json == null) {
    return json;
  }
  return {
    dimensionKeys:
      json["dimensionKeys"] == null ? undefined : json["dimensionKeys"],
    dimensionValues:
      json["dimensionValues"] == null ? undefined : json["dimensionValues"],
  };
}

export function TrendToJSON(json: any): Trend {
  return TrendToJSONTyped(json, false);
}

export function TrendToJSONTyped(
  value?: Trend | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    dimensionKeys: value["dimensionKeys"],
    dimensionValues: value["dimensionValues"],
  };
}
