[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-include-markdown-plugin>=7.2.0",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.21",
    "pymdown-extensions>=10.16.1",
]
