/* tslint:disable */
/* eslint-disable */
/**
 * Grading API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GradeQuestion
 */
export interface GradeQuestion {
  /**
   *
   * @type {number}
   * @memberof GradeQuestion
   */
  points: number;
  /**
   *
   * @type {string}
   * @memberof GradeQuestion
   */
  feedback: string;
}

/**
 * Check if a given object implements the GradeQuestion interface.
 */
export function instanceOfGradeQuestion(value: object): value is GradeQuestion {
  if (!("points" in value) || value["points"] === undefined) return false;
  if (!("feedback" in value) || value["feedback"] === undefined) return false;
  return true;
}

export function GradeQuestionFromJSON(json: any): GradeQuestion {
  return GradeQuestionFromJSONTyped(json, false);
}

export function GradeQuestionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GradeQuestion {
  if (json == null) {
    return json;
  }
  return {
    points: json["points"],
    feedback: json["feedback"],
  };
}

export function GradeQuestionToJSON(json: any): GradeQuestion {
  return GradeQuestionToJSONTyped(json, false);
}

export function GradeQuestionToJSONTyped(
  value?: GradeQuestion | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    points: value["points"],
    feedback: value["feedback"],
  };
}
