// Package api_client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api_client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Api_keyScopes    = "api_key.Scopes"
	Basic_authScopes = "basic_auth.Scopes"
)

// Exam defines model for Exam.
type Exam struct {
	// CreatedAt The creation timestamp of the entity
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Deleted Indicates if the entity is deleted
	Deleted *bool `json:"deleted,omitempty"`

	// DeletedAt The deletion timestamp of the entity, if applicable
	DeletedAt *time.Time `json:"deletedAt"`

	// GradeLevel The grade level for which the exam is intended
	GradeLevel *int    `json:"gradeLevel,omitempty"`
	Id         *string `json:"id,omitempty"`

	// Name The name of the Exam
	Name      *string         `json:"name,omitempty"`
	Questions *[]ExamQuestion `json:"questions,omitempty"`

	// UpdatedAt The last update timestamp of the entity
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// ExamMetadata An Exam entity containing exam metadata
type ExamMetadata struct {
	// CreatedAt The creation timestamp of the entity
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Deleted Indicates if the entity is deleted
	Deleted *bool `json:"deleted,omitempty"`

	// DeletedAt The deletion timestamp of the entity, if applicable
	DeletedAt *time.Time `json:"deletedAt"`

	// GradeLevel The grade level for which the exam is intended
	GradeLevel *int    `json:"gradeLevel,omitempty"`
	Id         *string `json:"id,omitempty"`

	// Name The name of the Exam
	Name *string `json:"name,omitempty"`

	// UpdatedAt The last update timestamp of the entity
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// ExamQuestion A question within an Exam, including the question text, possible answers, and the correct answer.
type ExamQuestion struct {
	// CorrectAnswer The correct answer to the question
	CorrectAnswer *string `json:"correctAnswer,omitempty"`
	ExamID        *string `json:"examID,omitempty"`
	Id            *string `json:"id,omitempty"`

	// PossibleAnswers A list of possible answers for the question
	PossibleAnswers *[]string `json:"possibleAnswers,omitempty"`

	// QuestionText The text of the question
	QuestionText *string `json:"questionText,omitempty"`
}

// Exams A list of Exam entities.
type Exams = []ExamMetadata

// PostAddExamToLibraryJSONRequestBody defines body for PostAddExamToLibrary for application/json ContentType.
type PostAddExamToLibraryJSONRequestBody = Exam

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetFindAllExams request
	GetFindAllExams(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAddExamToLibraryWithBody request with any body
	PostAddExamToLibraryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAddExamToLibrary(ctx context.Context, body PostAddExamToLibraryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetFindOneByID request
	GetFindOneByID(ctx context.Context, examID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetFindAllExams(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetFindAllExamsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAddExamToLibraryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAddExamToLibraryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAddExamToLibrary(ctx context.Context, body PostAddExamToLibraryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAddExamToLibraryRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetFindOneByID(ctx context.Context, examID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetFindOneByIDRequest(c.Server, examID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetFindAllExamsRequest generates requests for GetFindAllExams
func NewGetFindAllExamsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/exams")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostAddExamToLibraryRequest calls the generic PostAddExamToLibrary builder with application/json body
func NewPostAddExamToLibraryRequest(server string, body PostAddExamToLibraryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAddExamToLibraryRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAddExamToLibraryRequestWithBody generates requests for PostAddExamToLibrary with any type of body
func NewPostAddExamToLibraryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/exams")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetFindOneByIDRequest generates requests for GetFindOneByID
func NewGetFindOneByIDRequest(server string, examID openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "examID", runtime.ParamLocationPath, examID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/exams/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetFindAllExamsWithResponse request
	GetFindAllExamsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetFindAllExamsResponse, error)

	// PostAddExamToLibraryWithBodyWithResponse request with any body
	PostAddExamToLibraryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAddExamToLibraryResponse, error)

	PostAddExamToLibraryWithResponse(ctx context.Context, body PostAddExamToLibraryJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAddExamToLibraryResponse, error)

	// GetFindOneByIDWithResponse request
	GetFindOneByIDWithResponse(ctx context.Context, examID openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetFindOneByIDResponse, error)
}

type GetFindAllExamsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Exams
}

// Status returns HTTPResponse.Status
func (r GetFindAllExamsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFindAllExamsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAddExamToLibraryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Exam
}

// Status returns HTTPResponse.Status
func (r PostAddExamToLibraryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAddExamToLibraryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetFindOneByIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Exam
}

// Status returns HTTPResponse.Status
func (r GetFindOneByIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFindOneByIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetFindAllExamsWithResponse request returning *GetFindAllExamsResponse
func (c *ClientWithResponses) GetFindAllExamsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetFindAllExamsResponse, error) {
	rsp, err := c.GetFindAllExams(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetFindAllExamsResponse(rsp)
}

// PostAddExamToLibraryWithBodyWithResponse request with arbitrary body returning *PostAddExamToLibraryResponse
func (c *ClientWithResponses) PostAddExamToLibraryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAddExamToLibraryResponse, error) {
	rsp, err := c.PostAddExamToLibraryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAddExamToLibraryResponse(rsp)
}

func (c *ClientWithResponses) PostAddExamToLibraryWithResponse(ctx context.Context, body PostAddExamToLibraryJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAddExamToLibraryResponse, error) {
	rsp, err := c.PostAddExamToLibrary(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAddExamToLibraryResponse(rsp)
}

// GetFindOneByIDWithResponse request returning *GetFindOneByIDResponse
func (c *ClientWithResponses) GetFindOneByIDWithResponse(ctx context.Context, examID openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetFindOneByIDResponse, error) {
	rsp, err := c.GetFindOneByID(ctx, examID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetFindOneByIDResponse(rsp)
}

// ParseGetFindAllExamsResponse parses an HTTP response from a GetFindAllExamsWithResponse call
func ParseGetFindAllExamsResponse(rsp *http.Response) (*GetFindAllExamsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetFindAllExamsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Exams
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostAddExamToLibraryResponse parses an HTTP response from a PostAddExamToLibraryWithResponse call
func ParsePostAddExamToLibraryResponse(rsp *http.Response) (*PostAddExamToLibraryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAddExamToLibraryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Exam
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetFindOneByIDResponse parses an HTTP response from a GetFindOneByIDWithResponse call
func ParseGetFindOneByIDResponse(rsp *http.Response) (*GetFindOneByIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetFindOneByIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Exam
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
